import { NextResponse } from "next/server";
import { createClient } from "@/utils/supabase/server";

export async function GET() {
  try {
    const supabase = await createClient();

    // Fetch records from free_assets table sorted by created_at desc
    const { data: files, error } = await supabase
      .from("free_assets")
      .select("*")
      .order("created_at", { ascending: false });

    if (error) {
      throw new Error(`Database fetch failed: ${error.message}`);
    }

    // Extract unique uploader emails to query nicknames from profiles table
    const uploaderEmails = Array.from(
      new Set(
        (files || [])
          .map((f) => f.uploader)
          .filter((u): u is string => !!u && u.includes("@"))
      )
    );

    // Map emails to nicknames dynamically
    const emailToNicknameMap: Record<string, string> = {};
    if (uploaderEmails.length > 0) {
      const { data: profiles, error: profilesError } = await supabase
        .from("profiles")
        .select("email, nickname")
        .in("email", uploaderEmails);

      if (!profilesError && profiles) {
        profiles.forEach((p) => {
          if (p.email && p.nickname) {
            emailToNicknameMap[p.email.toLowerCase()] = p.nickname;
          }
        });
      }
    }

    const formattedFiles = (files || []).map((file) => {
      const emailKey = file.uploader ? file.uploader.toLowerCase() : "";
      const displayUploader = emailToNicknameMap[emailKey] || file.uploader;

      return {
        id: file.gdrive_file_id,
        name: file.file_name,
        url: file.storage_url,
        mimeType: file.mime_type,
        size: file.width ? 0 : 0,
        createdAt: file.created_at,
        title: file.title,
        tags: file.tags || [],
        mediaType: file.media_type,
        uploader: displayUploader,
        uploaderEmail: file.uploader || "",
        downloads: file.downloads_count || 0,
        views: file.views_count || 0,
        aspectRatio: file.aspect_ratio || "",
        generationType: file.generation_type || "real",
        width: file.width || 0,
        height: file.height || 0,
        camera: file.camera || "촬영 정보 없음",
        prompt: file.prompt || "",
        aiTool: file.ai_tool || "",
        isOfficialThemeAsset: file.is_official_theme_asset || false,
        themeCategory: file.theme_category || "",
        isBusinessOnly: file.is_business_only || false,
      };
    });

    const staticCategoryAssets = [
      {
        id: "cat-art-static",
        name: "art_category.png",
        url: "/images/categories/art.png",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "추상 기하학 입체 그래픽 아트",
        tags: ["art", "예술", "창작", "추상", "graphic", "illustration", "design", "geometric", "3d"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 120,
        views: 340,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "Midjourney v6.0",
        prompt: "Vibrant abstract geometric background, premium 3D shapes render, shutterstock style category cover, high contrast, clean studio lighting",
        aiTool: "Midjourney",
        isOfficialThemeAsset: false,
        themeCategory: "art",
        isBusinessOnly: false,
      },
      {
        id: "cat-tech-static",
        name: "tech_category.png",
        url: "/images/categories/tech.png",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "미래 지향적 사이버 보안 네트워크 홀로그램",
        tags: ["tech", "기술", "디지털", "hologram", "cyber", "digital", "network", "security"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 95,
        views: 280,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "Stable Diffusion XL",
        prompt: "Futuristic digital network hologram, cyber security glowing abstract binary, shutterstock style category cover, dark background, 3d abstract render",
        aiTool: "Stable Diffusion",
        isOfficialThemeAsset: false,
        themeCategory: "tech",
        isBusinessOnly: false,
      },
      {
        id: "cat-food-static",
        name: "food_category.png",
        url: "/images/categories/food.png",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "프리미엄 수제 치즈버거와 감자튀김 그리고 수제 맥주",
        tags: ["food", "미식", "푸드", "음식", "요리", "burger", "beer", "fries", "hamburger", "gourmet"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 145,
        views: 420,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "DALL-E 3",
        prompt: "Delicious classic gourmet burger with melting cheese, crispy bacon, fries and cold beer next to it, warm restaurant lighting, premium food photography, shutterstock style cover",
        aiTool: "DALL-E 3",
        isOfficialThemeAsset: false,
        themeCategory: "food",
        isBusinessOnly: false,
      },
      {
        id: "cat-nature-static",
        name: "nature_category.png",
        url: "/images/categories/nature.png",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "스위스 만년설 산맥과 붉은 열차 풍경",
        tags: ["nature", "자연", "풍경", "forest", "mountain", "river", "train", "landscape", "scenic"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 230,
        views: 510,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "Midjourney v6.0",
        prompt: "Beautiful scenic landscape with a red train crossing a bridge, green pine forest and majestic snowcapped mountains in the background, cinematic sunset lighting, shutterstock style cover",
        aiTool: "Midjourney",
        isOfficialThemeAsset: false,
        themeCategory: "nature",
        isBusinessOnly: false,
      },
      {
        id: "cat-animal-static",
        name: "lion.jpg",
        url: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "초원을 거니는 야생 사자 야생동물 포토",
        tags: ["animal", "동물", "야생", "lion", "cat", "dog", "wildlife", "safari"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 80,
        views: 190,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Sony A7R V - FE 200-600mm",
        prompt: "Wildlife photograph of a male lion walking in dry grass safari sunset",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "animal",
        isBusinessOnly: false,
      },
      {
        id: "cat-texture-static",
        name: "texture.jpg",
        url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "추상 물감 텍스처 배경 아트 일러스트",
        tags: ["texture", "텍스처", "background", "배경", "abstract", "art", "paint"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 110,
        views: 290,
        aspectRatio: "4:3",
        generationType: "real",
        width: 1200,
        height: 900,
        camera: "Canon EOS R5",
        prompt: "Abstract colorful oil paint brush stroke texture wallpaper background",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "texture",
        isBusinessOnly: false,
      },
      {
        id: "cat-people-static",
        name: "elon_musk_portrait.jpg",
        url: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Elon_Musk_Royal_Society.jpg",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "테슬라 CEO 일론 머스크 공식 인물 라이프 (세로형)",
        tags: ["people", "인물", "라이프", "person", "man", "woman", "elon", "musk", "ceo", "portrait"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 380,
        views: 950,
        aspectRatio: "9:16",
        generationType: "real",
        width: 1080,
        height: 1920,
        camera: "Nikon D850",
        prompt: "Official portrait of Tesla and SpaceX CEO Elon Musk, vertical format",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "people",
        isBusinessOnly: false,
      },
      {
        id: "cat-people-landscape-static",
        name: "elon_musk_landscape.jpg",
        url: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Elon_Musk_Royal_Society.jpg",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "테슬라 CEO 일론 머스크 상반신 프로필 (가로형)",
        tags: ["people", "인물", "라이프", "person", "man", "woman", "elon", "musk", "ceo", "landscape"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 410,
        views: 1050,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Nikon D850",
        prompt: "Official landscape profile of Tesla and SpaceX CEO Elon Musk, head and shoulders shot",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "people",
        isBusinessOnly: false,
      },
      {
        id: "cat-architecture-static",
        name: "skyscraper.jpg",
        url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "현대식 초고층 빌딩 랜드마크 건축",
        tags: ["architecture", "건축", "랜드마크", "building", "skyscraper", "city", "modern"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 140,
        views: 310,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Fujifilm GFX 100S",
        prompt: "Worm's eye view of glass skyscraper office building architectural photogaphy",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "architecture",
        isBusinessOnly: false,
      },
      {
        id: "cat-fashion-static",
        name: "fashion.jpg",
        url: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "세련된 쇼핑 런웨이 패션 & 뷰티 라이프",
        tags: ["fashion", "패션", "뷰티", "beauty", "model", "shopping", "clothes"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 195,
        views: 440,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Leica SL2",
        prompt: "High fashion model carrying shopping bags street styling",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "fashion",
        isBusinessOnly: false,
      },
      {
        id: "cat-business-static",
        name: "business.jpg",
        url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "기업 오피스 비즈니스 및 금융 마케팅 차트",
        tags: ["business", "비즈니스", "금융", "finance", "office", "marketing", "chart", "corporate"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 170,
        views: 395,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Sony A7IV",
        prompt: "Financial charts on laptop screen in modern business office workspace",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "business",
        isBusinessOnly: false,
      },
      {
        id: "cat-education-static",
        name: "education.jpg",
        url: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "도서관 책 더미와 사과 교육 & 지식",
        tags: ["education", "교육", "지식", "book", "school", "library", "learning", "study"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 155,
        views: 360,
        aspectRatio: "4:3",
        generationType: "real",
        width: 1200,
        height: 900,
        camera: "Canon 5D Mark IV",
        prompt: "Stack of books with red apple on top school classroom study concept",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "education",
        isBusinessOnly: false,
      },
      {
        id: "cat-health-static",
        name: "health.jpg",
        url: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "청진기와 검진 침대 의료 & 헬스케어",
        tags: ["health", "의료", "헬스케어", "medical", "hospital", "doctor", "stethoscope"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 130,
        views: 295,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Sony A7III",
        prompt: "Stethoscope lying on medical chart hospital doctor workspace",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "health",
        isBusinessOnly: false,
      }
    ];

    return NextResponse.json({ files: [...formattedFiles, ...staticCategoryAssets] });
  } catch (error: any) {
    console.error("Failed to list free assets from database:", error);
    return NextResponse.json(
      { error: "Database query error", details: error.message },
      { status: 500 }
    );
  }
}
