import { NextResponse } from "next/server";
import { createClient } from "@/utils/supabase/server";
import fs from "fs";
import path from "path";

export async function GET() {
  try {
    const supabase = await createClient();

    // Fetch records from free_assets table sorted by created_at desc
    const { data: files, error } = await supabase
      .from("free_assets")
      .select("*")
      .order("created_at", { ascending: false });

    if (error) {
      throw new Error(`Database fetch failed: ${error.message}`);
    }

    // Load music assets dynamically from local metadata JSON
    let musicAssets: any[] = [];
    try {
      const metadataPath = path.resolve(process.cwd(), "src/lib/constants/music_metadata.json");
      if (fs.existsSync(metadataPath)) {
        const rawMetadata = fs.readFileSync(metadataPath, "utf-8");
        const parsed = JSON.parse(rawMetadata);
        
        const moodMap: Record<string, string> = {
          "upbeat": "경쾌한",
          "horror": "공포",
          "cute": "귀여운",
          "groovy": "그루브",
          "suspenseful": "긴장감",
          "minimal": "단순한",
          "dramatic": "드라마틱",
          "romantic": "로맨틱",
          "dreamy": "몽환적인",
          "bright": "밝은",
          "solemn": "비장한",
          "sad": "슬픈",
          "exciting": "신나는",
          "mysterious": "신비로운",
          "nostalgic": "아련한",
          "epic": "웅장한",
          "calm": "잔잔한",
          "fun": "재밌는",
          "refreshing": "청량한",
          "comical": "코믹한",
          "peaceful": "평온한",
          "happy": "행복한",
          "hopeful": "희망찬",
          "scary": "무서운"
        };

        musicAssets = parsed.map((song: any) => {
          // Normalize subgenre for WebP thumbnail URL mapping
          const cleanSubGenre = song.subGenre.replace(/[^a-zA-Z0-9]/g, "_");
          return {
            id: song.id,
            name: `${song.title}.mp3`,
            url: song.audioUrl,
            thumbnailUrl: `/images/genres/${cleanSubGenre}.webp`,
            mimeType: "audio/mpeg",
            size: 0,
            createdAt: new Date().toISOString(),
            title: song.title,
            // Bundle all metadata into tags so they are correctly searchable and filterable by genre and mood
            tags: [
              song.subGenre.toLowerCase(),
              song.genreGroup.toLowerCase(),
              song.mood.toLowerCase(),
              "music",
              "bgm",
              "음악",
              "사운드",
              ...song.mood.split(",").map((m: string) => m.trim().toLowerCase()),
              ...song.mood.split(",").map((m: string) => {
                const norm = m.trim().toLowerCase();
                return moodMap[norm] || "";
              }).filter(Boolean)
            ],
            mediaType: "music",
            uploader: "CreAIbox Official",
            uploaderEmail: "admin@creaibox.com",
            downloads: Math.floor(Math.random() * 120) + 10,
            views: Math.floor(Math.random() * 300) + 50,
            aspectRatio: "",
            generationType: "ai",
            width: 0,
            height: 0,
            camera: "",
            prompt: song.prompt || "",
            aiTool: "Suno / Udio",
            isOfficialThemeAsset: false,
            themeCategory: "music",
            isBusinessOnly: false,
          };
        });
      }
    } catch (e) {
      console.error("Failed to load music metadata json in API:", e);
    }

    // Extract unique uploader emails to query nicknames from profiles table
    const uploaderEmails = Array.from(
      new Set(
        (files || [])
          .map((f) => f.uploader)
          .filter((u): u is string => !!u && u.includes("@"))
      )
    );

    // Map emails to nicknames dynamically
    const emailToNicknameMap: Record<string, string> = {};
    if (uploaderEmails.length > 0) {
      const { data: profiles, error: profilesError } = await supabase
        .from("profiles")
        .select("email, nickname")
        .in("email", uploaderEmails);

      if (!profilesError && profiles) {
        profiles.forEach((p) => {
          if (p.email && p.nickname) {
            emailToNicknameMap[p.email.toLowerCase()] = p.nickname;
          }
        });
      }
    }

    const formattedFiles = (files || []).map((file) => {
      const emailKey = file.uploader ? file.uploader.toLowerCase() : "";
      const displayUploader = emailToNicknameMap[emailKey] || file.uploader;

      return {
        id: file.gdrive_file_id,
        name: file.file_name,
        url: file.storage_url,
        thumbnailUrl: file.thumbnail_url || "",
        mimeType: file.mime_type,
        size: file.width ? 0 : 0,
        createdAt: file.created_at,
        title: file.title,
        tags: file.tags || [],
        mediaType: file.media_type,
        uploader: displayUploader,
        uploaderEmail: file.uploader || "",
        downloads: file.downloads_count || 0,
        views: file.views_count || 0,
        aspectRatio: file.aspect_ratio || "",
        generationType: file.generation_type || "real",
        width: file.width || 0,
        height: file.height || 0,
        camera: file.camera || "촬영 정보 없음",
        prompt: file.prompt || "",
        aiTool: file.ai_tool || "",
        isOfficialThemeAsset: file.is_official_theme_asset || false,
        themeCategory: file.theme_category || "",
        isBusinessOnly: file.is_business_only || false,
      };
    });

    const staticCategoryAssets = [
      {
        id: "cat-art-static",
        name: "art_category.webp",
        url: "/images/categories/art.webp",
        mimeType: "image/webp",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "추상 기하학 입체 그래픽 아트",
        tags: ["art", "예술", "창작", "추상", "graphic", "illustration", "design", "geometric", "3d"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 120,
        views: 340,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "Midjourney v6.0",
        prompt: "Vibrant abstract geometric background, premium 3D shapes render, shutterstock style category cover, high contrast, clean studio lighting",
        aiTool: "Midjourney",
        isOfficialThemeAsset: false,
        themeCategory: "art",
        isBusinessOnly: false,
      },
      {
        id: "cat-tech-static",
        name: "tech_category.webp",
        url: "/images/categories/tech.webp",
        mimeType: "image/webp",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "미래 지향적 사이버 보안 네트워크 홀로그램",
        tags: ["tech", "기술", "디지털", "hologram", "cyber", "digital", "network", "security"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 95,
        views: 280,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "Stable Diffusion XL",
        prompt: "Futuristic digital network hologram, cyber security glowing abstract binary, shutterstock style category cover, dark background, 3d abstract render",
        aiTool: "Stable Diffusion",
        isOfficialThemeAsset: false,
        themeCategory: "tech",
        isBusinessOnly: false,
      },
      {
        id: "cat-food-static",
        name: "food_category.webp",
        url: "/images/categories/food.webp",
        mimeType: "image/webp",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "프리미엄 수제 치즈버거와 감자튀김 그리고 수제 맥주",
        tags: ["food", "미식", "푸드", "음식", "요리", "burger", "beer", "fries", "hamburger", "gourmet"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 145,
        views: 420,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "DALL-E 3",
        prompt: "Delicious classic gourmet burger with melting cheese, crispy bacon, fries and cold beer next to it, warm restaurant lighting, premium food photography, shutterstock style cover",
        aiTool: "DALL-E 3",
        isOfficialThemeAsset: false,
        themeCategory: "food",
        isBusinessOnly: false,
      },
      {
        id: "cat-nature-static",
        name: "nature_category.webp",
        url: "/images/categories/nature.webp",
        mimeType: "image/webp",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "스위스 만년설 산맥과 붉은 열차 풍경",
        tags: ["nature", "자연", "풍경", "forest", "mountain", "river", "train", "landscape", "scenic"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 230,
        views: 510,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "Midjourney v6.0",
        prompt: "Beautiful scenic landscape with a red train crossing a bridge, green pine forest and majestic snowcapped mountains in the background, cinematic sunset lighting, shutterstock style cover",
        aiTool: "Midjourney",
        isOfficialThemeAsset: false,
        themeCategory: "nature",
        isBusinessOnly: false,
      },
      {
        id: "cat-animal-static",
        name: "lion.jpg",
        url: "https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "초원을 거니는 야생 사자 야생동물 포토",
        tags: ["animal", "동물", "야생", "lion", "cat", "dog", "wildlife", "safari"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 80,
        views: 190,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Sony A7R V - FE 200-600mm",
        prompt: "Wildlife photograph of a male lion walking in dry grass safari sunset",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "animal",
        isBusinessOnly: false,
      },
      {
        id: "cat-texture-static",
        name: "texture.jpg",
        url: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "추상 물감 텍스처 배경 아트 일러스트",
        tags: ["texture", "텍스처", "background", "배경", "abstract", "art", "paint"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 110,
        views: 290,
        aspectRatio: "4:3",
        generationType: "real",
        width: 1200,
        height: 900,
        camera: "Canon EOS R5",
        prompt: "Abstract colorful oil paint brush stroke texture wallpaper background",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "texture",
        isBusinessOnly: false,
      },
      {
        id: "cat-people-static",
        name: "elon_musk_portrait.jpg",
        url: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Elon_Musk_Royal_Society.jpg",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "테슬라 CEO 일론 머스크 공식 인물 라이프 (세로형)",
        tags: ["people", "인물", "라이프", "person", "man", "woman", "elon", "musk", "ceo", "portrait"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 380,
        views: 950,
        aspectRatio: "9:16",
        generationType: "real",
        width: 1080,
        height: 1920,
        camera: "Nikon D850",
        prompt: "Official portrait of Tesla and SpaceX CEO Elon Musk, vertical format",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "people",
        isBusinessOnly: false,
      },
      {
        id: "cat-people-landscape-static",
        name: "elon_musk_landscape.jpg",
        url: "https://upload.wikimedia.org/wikipedia/commons/e/ed/Elon_Musk_Royal_Society.jpg",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "테슬라 CEO 일론 머스크 상반신 프로필 (가로형)",
        tags: ["people", "인물", "라이프", "person", "man", "woman", "elon", "musk", "ceo", "landscape"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 410,
        views: 1050,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Nikon D850",
        prompt: "Official landscape profile of Tesla and SpaceX CEO Elon Musk, head and shoulders shot",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "people",
        isBusinessOnly: false,
      },
      {
        id: "cat-architecture-static",
        name: "skyscraper.jpg",
        url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "현대식 초고층 빌딩 랜드마크 건축",
        tags: ["architecture", "건축", "랜드마크", "building", "skyscraper", "city", "modern"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 140,
        views: 310,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Fujifilm GFX 100S",
        prompt: "Worm's eye view of glass skyscraper office building architectural photogaphy",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "architecture",
        isBusinessOnly: false,
      },
      {
        id: "cat-fashion-static",
        name: "fashion.jpg",
        url: "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "세련된 쇼핑 런웨이 패션 & 뷰티 라이프",
        tags: ["fashion", "패션", "뷰티", "beauty", "model", "shopping", "clothes"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 195,
        views: 440,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Leica SL2",
        prompt: "High fashion model carrying shopping bags street styling",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "fashion",
        isBusinessOnly: false,
      },
      {
        id: "cat-business-static",
        name: "business.jpg",
        url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "기업 오피스 비즈니스 및 금융 마케팅 차트",
        tags: ["business", "비즈니스", "금융", "finance", "office", "marketing", "chart", "corporate"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 170,
        views: 395,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Sony A7IV",
        prompt: "Financial charts on laptop screen in modern business office workspace",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "business",
        isBusinessOnly: false,
      },
      {
        id: "cat-education-static",
        name: "education.jpg",
        url: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "도서관 책 더미와 사과 교육 & 지식",
        tags: ["education", "교육", "지식", "book", "school", "library", "learning", "study"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 155,
        views: 360,
        aspectRatio: "4:3",
        generationType: "real",
        width: 1200,
        height: 900,
        camera: "Canon 5D Mark IV",
        prompt: "Stack of books with red apple on top school classroom study concept",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "education",
        isBusinessOnly: false,
      },
      {
        id: "cat-health-static",
        name: "health.jpg",
        url: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=600&q=80",
        mimeType: "image/jpeg",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "청진기와 검진 침대 의료 & 헬스케어",
        tags: ["health", "의료", "헬스케어", "medical", "hospital", "doctor", "stethoscope"],
        mediaType: "image",
        uploader: "CreAIbox Official",
        uploaderEmail: "admin@creaibox.com",
        downloads: 130,
        views: 295,
        aspectRatio: "16:9",
        generationType: "real",
        width: 1920,
        height: 1080,
        camera: "Sony A7III",
        prompt: "Stethoscope lying on medical chart hospital doctor workspace",
        aiTool: "",
        isOfficialThemeAsset: false,
        themeCategory: "health",
        isBusinessOnly: false,
      },
      {
        id: "cat-tech-new-static-1",
        name: "asset_1.png",
        url: "https://drive.google.com/uc?export=download&id=1TospF6xHC0yTjh41gEkzMIrYmYP0rpa4",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "AI 시냅스 뉴럴 네트워크 브레인",
        tags: ["tech", "기술", "디지털", "brain", "ai", "neural", "synapse"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 450,
        views: 1200,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "",
        prompt: "A futuristic AI neural network brain glowing with synaptic connections, isometric vector style",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "tech",
        isBusinessOnly: false,
      },
      {
        id: "cat-food-new-static-2",
        name: "asset_2.png",
        url: "https://drive.google.com/uc?export=download&id=11xXAo4qiZE7wx0SegYn_IYvhzlouyI0q",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "더블 치즈버거와 수제 크리스피 감자튀김",
        tags: ["food", "미식", "푸드", "burger", "french fries", "gourmet", "cheese"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 320,
        views: 890,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "",
        prompt: "A premium delicious gourmet double cheeseburger with fresh ingredients and crispy fries on a rustic wooden plate",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "food",
        isBusinessOnly: false,
      },
      {
        id: "cat-nature-new-static-3",
        name: "asset_3.png",
        url: "https://drive.google.com/uc?export=download&id=1Jg4vepBE5DRdH6uDSn5FEoJHk6C2cmcc",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "신비로운 야간 버섯 요정의 숲",
        tags: ["nature", "자연", "풍경", "forest", "mushroom", "fantasy", "glowing", "fairy"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 510,
        views: 1420,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "",
        prompt: "A magical glowing forest at night with bioluminescent mushrooms and glowing pollen floating",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "nature",
        isBusinessOnly: false,
      },
      {
        id: "cat-people-new-static-4",
        name: "asset_4.png",
        url: "https://drive.google.com/uc?export=download&id=1Amlm3JwJDhHRXGWUCA1XAuo7cRY4rfJy",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "AI 미래 스튜디오에서 작업 중인 디자이너",
        tags: ["people", "인물", "라이프", "designer", "studio", "neon", "workstation", "creative"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 290,
        views: 740,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "",
        prompt: "A stylish modern creative designer working in a futuristic neon-lit office studio",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "people",
        isBusinessOnly: false,
      },
      {
        id: "cat-architecture-new-static-5",
        name: "asset_5.png",
        url: "https://drive.google.com/uc?export=download&id=1GI2CYQDscjuhf43yKDwataPiIIDvnu7-",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "공중 인공폭포가 흐르는 에코 마천루 빌딩",
        tags: ["architecture", "건축", "랜드마크", "skyscraper", "building", "eco", "garden", "waterfall"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 380,
        views: 920,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "",
        prompt: "A futuristic eco-friendly skyscraper building covered in lush vertical gardens and cascading waterfalls",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "architecture",
        isBusinessOnly: false,
      },
      {
        id: "cat-fashion-new-static-6",
        name: "asset_6.png",
        url: "https://drive.google.com/uc?export=download&id=1StoAHSe53KjIjhpf2DVsmD3aKvpSqV3b",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "네온 크롬 아방가르드 하이패션 화보",
        tags: ["fashion", "패션", "뷰티", "model", "cyberpunk", "metallic", "chrome", "neon"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 410,
        views: 1150,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "",
        prompt: "A chic model wearing avant-garde metallic chrome clothing, neon pink studio lighting",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "fashion",
        isBusinessOnly: false,
      },
      {
        id: "cat-business-new-static-7",
        name: "asset_7.png",
        url: "https://drive.google.com/uc?export=download&id=1L0jerxlTgKs80eQ0n1EdYv0g8KtGefzB",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "사이버펑크 시티뷰 비즈니스 회의실",
        tags: ["business", "비즈니스", "금융", "meeting", "office", "skyline", "cityview", "consulting"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 250,
        views: 680,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "",
        prompt: "A sleek modern office meeting room overlooking a futuristic cyberpunk city skyline at twilight",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "business",
        isBusinessOnly: false,
      },
      {
        id: "cat-education-new-static-8",
        name: "asset_8.png",
        url: "https://drive.google.com/uc?export=download&id=12ecmDSnhunrjoJhty_O5_KirVFWuvJDF",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "마법사의 서재와 둥둥 떠다니는 고서적",
        tags: ["education", "교육", "지식", "wizard", "library", "magic", "book", "school"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 490,
        views: 1380,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "",
        prompt: "An ancient wizard's library room filled with magical glowing spell books floating in mid-air",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "education",
        isBusinessOnly: false,
      },
      {
        id: "cat-health-new-static-9",
        name: "asset_9.png",
        url: "https://drive.google.com/uc?export=download&id=109_-QeOmhGadF8OCWn4QxxChcUFKf1HG",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "홀로그램 DNA 디스플레이와 바이오 바이러스 검진",
        tags: ["health", "의료", "헬스케어", "medical", "dna", "lab", "biotech", "science"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 300,
        views: 820,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "",
        prompt: "A futuristic holographic medical diagnosis display showing a DNA strand and heart rate monitors in a clean lab",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "health",
        isBusinessOnly: false,
      },
      {
        id: "cat-art-new-static-10",
        name: "asset_10.png",
        url: "https://drive.google.com/uc?export=download&id=1r6UoCznIPGRoAqowzgaJbqqJet8wBzCu",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "홀로그래픽 액체 추상 미술 아크릴 스플래시",
        tags: ["art", "추상", "그래픽", "liquid", "acrylic", "paint", "abstract", "holographic"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 580,
        views: 1650,
        aspectRatio: "1:1",
        generationType: "ai",
        width: 1024,
        height: 1024,
        camera: "",
        prompt: "Abstract fluid acrylic splash art, vibrant holographic liquid colors swirling together",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "art",
        isBusinessOnly: false,
      },
      {
        id: "cat-art-real-static-11",
        name: "asset_11.png",
        url: "https://drive.google.com/uc?export=download&id=1XqeVzZDfohDIY1xHSb08bqslglL07jrh",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "홀로그래픽 물감 물방울 추상화",
        tags: ["art", "추상", "그래픽", "liquid", "acrylic", "paint", "abstract", "holographic", "splash"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 410,
        views: 1100,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "Close-up photorealistic shot of glowing colorful holographic paint swirling in clear water, high-speed photography, dynamic fluid motion",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "art",
        isBusinessOnly: false,
      },
      {
        id: "cat-tech-real-static-12",
        name: "asset_12.png",
        url: "https://drive.google.com/uc?export=download&id=14Jk2pcS6Cjn2fzTDFnt3GU3d03af5-Bo",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "인공지능 초고속 데이터 센터 서버룸",
        tags: ["tech", "기술", "디지털", "server", "data center", "cables", "led", "cloud"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 380,
        views: 920,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "A clean high-tech server room with glowing blue and green led cables, photorealistic interior design, futuristic AI data center",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "tech",
        isBusinessOnly: false,
      },
      {
        id: "cat-food-real-static-13",
        name: "asset_13.png",
        url: "https://drive.google.com/uc?export=download&id=1qf-nck5sK4bPyO5pWTJCl0msw81lGK3p",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "수제 차슈 돈코츠 라멘",
        tags: ["food", "미식", "푸드", "ramen", "japanese food", "pork", "egg", "noodle"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 620,
        views: 1720,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "An authentic hot steaming bowl of fresh Japanese ramen with pork belly slices, soft half-boiled egg, green onions",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "food",
        isBusinessOnly: false,
      },
      {
        id: "cat-nature-real-static-14",
        name: "asset_14.png",
        url: "https://drive.google.com/uc?export=download&id=1MfvaOxUwzeqxAJi0L3d6PKpnAnoaitXh",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "에메랄드빛 바다와 그린 열대 섬",
        tags: ["nature", "자연", "풍경", "island", "ocean", "tropical", "aerial", "beach"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 480,
        views: 1350,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "Stunning aerial drone view of a lush green tropical island surrounded by crystal clear turquoise ocean water, sunny daytime",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "nature",
        isBusinessOnly: false,
      },
      {
        id: "cat-animal-real-static-15",
        name: "asset_15.png",
        url: "https://drive.google.com/uc?export=download&id=1bPAb7-rtVmMRMPxhwpEBUJdQ-Ybzex8N",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "초원의 왕 사자 골든아워 초상",
        tags: ["animal", "동물", "야생", "lion", "safari", "wildlife", "predator", "portrait"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 540,
        views: 1560,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "Stunning close-up portrait of a majestic lion staring directly at the camera, photorealistic animal photography, golden hour lighting",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "animal",
        isBusinessOnly: false,
      },
      {
        id: "cat-texture-real-static-16",
        name: "asset_16.png",
        url: "https://drive.google.com/uc?export=download&id=1-vlrbZpVyx-5XaI9wYfR8-m552KVh1O_",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "붉게 타오르는 숯불 목탄 텍스처",
        tags: ["texture", "배경", "텍스처", "charcoal", "embers", "fire", "coal", "dark"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 290,
        views: 840,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "A beautifully detailed macro texture of raw dark charcoal pieces with subtle orange glowing fire embers",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "texture",
        isBusinessOnly: false,
      },
      {
        id: "cat-people-real-static-17",
        name: "asset_17.png",
        url: "https://drive.google.com/uc?export=download&id=1BamM8gU37e3gXk_5F-nYuiF6h524nSdF",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "창가에서 커피를 마시는 미소 띤 여성",
        tags: ["people", "인물", "라이프", "woman", "coffee", "cafe", "rain", "portrait", "cozy"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 470,
        views: 1280,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "A beautiful young woman smiling warmly while drinking hot coffee next to a rain-streaked coffee shop window, cinematic lighting",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "people",
        isBusinessOnly: false,
      },
      {
        id: "cat-architecture-real-static-18",
        name: "asset_18.png",
        url: "https://drive.google.com/uc?export=download&id=1909H0XXwQgMNoLXMZa5iZ0-dWHrB742j",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "석양에 빛나는 하얀색 현대식 교각",
        tags: ["architecture", "건축", "랜드마크", "bridge", "river", "sunset", "modern", "design"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 360,
        views: 990,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "A majestic modern white architectural bridge crossing a clean river during sunset, golden hour light reflecting on metal and glass",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "architecture",
        isBusinessOnly: false,
      },
      {
        id: "cat-fashion-real-static-19",
        name: "asset_19.png",
        url: "https://drive.google.com/uc?export=download&id=1n2afDJ_bOJaQR2hOb4qTxaOSxxBDmSQ6",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "네온 아방가르드 스튜디오 패션 메이크업 화보",
        tags: ["fashion", "패션", "뷰티", "model", "makeup", "neon", "lip", "studio"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 430,
        views: 1210,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "A high-fashion editorial close-up of a model wearing colorful neon makeup and glossy skin under dramatic colorful studio lights",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "fashion",
        isBusinessOnly: false,
      },
      {
        id: "cat-business-real-static-20",
        name: "asset_20.png",
        url: "https://drive.google.com/uc?export=download&id=1-kf7K1zazPCHxBza1pR66W-qgOkRrn3F",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "금융 허브 빌딩 전망 비즈니스 오피스 데스크",
        tags: ["business", "비즈니스", "금융", "office", "laptop", "skyline", "workspace", "finance"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 280,
        views: 790,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "A sleek contemporary office workspace with a clean laptop, coffee cup, and notes, overlooking a modern financial district skyline through window",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "business",
        isBusinessOnly: false,
      },
      {
        id: "cat-education-real-static-21",
        name: "asset_21.png",
        url: "https://drive.google.com/uc?export=download&id=123LNr2g0VAuoXl2pJT5MvEcIiCuetLzE",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "빈티지 대도서관 공부 책상과 돋보기",
        tags: ["education", "교육", "지식", "library", "desk", "book", "glasses", "lamp", "vintage"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 500,
        views: 1410,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "A beautifully lit vintage library study desk with an open leather-bound book, reading glasses, and a warm desk lamp casting cozy light",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "education",
        isBusinessOnly: false,
      },
      {
        id: "cat-health-real-static-22",
        name: "asset_22.png",
        url: "https://drive.google.com/uc?export=download&id=1OsASY8H5y99PmjfAQFYarP6gtFezIx3W",
        mimeType: "image/png",
        size: 0,
        createdAt: new Date().toISOString(),
        title: "생명공학 식물 배양 실험실 현장",
        tags: ["health", "의료", "헬스케어", "lab", "biotech", "science", "plant", "research"],
        mediaType: "image",
        uploader: "CreAIbox AI Assistant",
        uploaderEmail: "assistant@creaibox.com",
        downloads: 320,
        views: 890,
        aspectRatio: "16:9",
        generationType: "ai",
        width: 1920,
        height: 1080,
        camera: "",
        prompt: "A professional modern laboratory research table with green plant seedlings in test tubes and petri dishes under grow lights, biotechnology",
        aiTool: "CreAibox Engine",
        isOfficialThemeAsset: false,
        themeCategory: "health",
        isBusinessOnly: false,
      }
    ];

    return NextResponse.json({ files: [...formattedFiles, ...staticCategoryAssets, ...musicAssets] });
  } catch (error: any) {
    console.error("Failed to list free assets from database:", error);
    return NextResponse.json(
      { error: "Database query error", details: error.message },
      { status: 500 }
    );
  }
}
