import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Contents Studio",
  description: "Generated by Creaibox.com",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#0a0c10]">
        {/* 🌟 헤더는 여기에 고정! 페이지가 바뀌어도 새로고침되지 않습니다. */}
        <Header /> 
        
        {/* 🌟 pt-20 삭제: 하위 레이아웃(InfoCenter 등)에서 이미 pt-20을 쓰고 있으므로,
          여기서 또 주면 이중으로 밀립니다. 하위 레이아웃이 없는 일반 페이지에서만 
          개별적으로 여백을 주시는 게 가장 깔끔합니다.
        */}
        <main className="flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}