import type { IdeaHubSeriesIdea } from "../types";

const CATEGORY_ID = "ai-tech";

function makeSeries(
  prefix: string,
  subTopicId: string,
  titles: string[],
  featuredIndexes: number[] = []
): IdeaHubSeriesIdea[] {
  return titles.map((title, index) => ({
    id: `${prefix}-${String(index + 1).padStart(3, "0")}`,
    categoryId: CATEGORY_ID,
    subTopicId,
    title,
    featured: featuredIndexes.includes(index + 1),
  }));
}

export const aiTechSeries: IdeaHubSeriesIdea[] = [
  ...makeSeries(
    "chatgpt",
    "chatgpt",
    [
      "ChatGPT란 무엇인가? 초보자를 위한 완벽 가이드",
      "2026 ChatGPT 활용법 BEST 10",
      "ChatGPT 무료와 유료 차이 총정리",
      "ChatGPT 프롬프트 작성법 완벽 정리",
      "직장인이 ChatGPT로 하루 1시간 절약하는 방법",
      "블로그 글쓰기에 ChatGPT 사용하는 방법",
      "ChatGPT로 돈 버는 방법 20가지",
      "ChatGPT API 사용법 완벽 정리",
      "ChatGPT와 Gemini 비교 분석",
      "ChatGPT와 Claude 비교 분석",
      "ChatGPT로 유튜브 대본 작성하는 방법",
      "ChatGPT로 쇼츠 아이디어 100개 만드는 방법",
      "ChatGPT 업무 자동화 사례 모음",
      "ChatGPT로 영어 공부하는 방법",
      "ChatGPT로 이력서 작성하는 방법",
      "ChatGPT 면접 준비 전략",
      "ChatGPT를 활용한 SEO 글쓰기 전략",
      "ChatGPT 블로그 자동화 구축 방법",
      "ChatGPT 최신 업데이트 총정리",
      "ChatGPT로 전자책 만드는 방법",
      "ChatGPT 마케팅 활용법",
      "ChatGPT와 Notion 조합 활용법",
      "ChatGPT와 Google Workspace 활용법",
      "ChatGPT로 고객 응대 자동화하는 방법",
      "ChatGPT로 회의록 정리하는 방법",
      "ChatGPT로 보고서 작성하는 방법",
      "ChatGPT로 사업계획서 작성하는 방법",
      "ChatGPT로 상품 설명문 작성하는 방법",
      "ChatGPT로 광고 카피 만드는 방법",
      "ChatGPT로 SNS 콘텐츠 기획하는 방법",
      "ChatGPT로 뉴스레터 작성하는 방법",
      "ChatGPT로 강의안 만드는 방법",
      "ChatGPT로 온라인 강의 기획하는 방법",
      "ChatGPT로 시장조사하는 방법",
      "ChatGPT로 경쟁사 분석하는 방법",
      "ChatGPT로 페르소나 설계하는 방법",
      "ChatGPT로 브랜드 전략 만드는 방법",
      "ChatGPT로 개발 공부하는 방법",
      "ChatGPT로 코드 리뷰하는 방법",
      "ChatGPT로 엑셀 업무 자동화하는 방법",
      "ChatGPT로 법률 문서 초안 작성하는 방법",
      "ChatGPT로 계약서 검토할 때 주의할 점",
      "ChatGPT로 여행 계획 세우는 방법",
      "ChatGPT로 독서 노트 정리하는 방법",
      "ChatGPT로 개인 비서처럼 사용하는 방법",
      "ChatGPT 사용 시 반드시 알아야 할 한계",
      "ChatGPT 개인정보 입력 시 주의사항",
      "ChatGPT 프롬프트 예시 50선",
      "ChatGPT 생산성 향상 워크플로우",
      "2026년에도 ChatGPT를 배워야 하는 이유",
    ],
    [1, 2, 7, 17, 50]
  ),

  ...makeSeries(
    "gemini",
    "gemini",
    [
      "Gemini란 무엇인가? Google AI 완벽 가이드",
      "Gemini 무료 사용법 총정리",
      "Gemini와 ChatGPT 차이점 비교",
      "Gemini와 Claude 비교 분석",
      "Gemini API 발급 및 사용법",
      "Gemini로 블로그 글 작성하는 방법",
      "Gemini로 최신 정보 기반 콘텐츠 만드는 방법",
      "Gemini 이미지 이해 기능 활용법",
      "Gemini로 유튜브 대본 만드는 방법",
      "Gemini로 업무 자동화하는 방법",
      "Gemini 프롬프트 작성법",
      "Gemini를 Google Workspace와 함께 쓰는 방법",
      "Gemini로 이메일 작성 자동화하기",
      "Gemini로 회의록 요약하는 방법",
      "Gemini로 리서치 자료 정리하는 방법",
      "Gemini로 SEO 콘텐츠 기획하는 방법",
      "Gemini로 마케팅 아이디어 만드는 방법",
      "Gemini로 보고서 초안 작성하는 방법",
      "Gemini 무료 모델과 유료 모델 차이",
      "2026 Gemini 최신 기능 총정리",
      "Gemini를 콘텐츠 제작에 활용하는 방법",
      "Gemini로 뉴스 요약 콘텐츠 만드는 방법",
      "Gemini로 상품 리뷰 글 작성하는 방법",
      "Gemini로 교육 자료 만드는 방법",
      "Gemini로 영어 공부하는 방법",
      "Gemini로 코딩 공부하는 방법",
      "Gemini API로 웹서비스 만드는 방법",
      "Gemini와 OpenAI API 비교",
      "Gemini 사용 시 주의해야 할 점",
      "Gemini를 배워야 하는 이유",
    ],
    [1, 3, 5, 20]
  ),

  ...makeSeries(
    "claude",
    "claude",
    [
      "Claude AI란 무엇인가? 초보자 가이드",
      "Claude 무료 사용법 총정리",
      "Claude와 ChatGPT 비교 분석",
      "Claude와 Gemini 비교 분석",
      "Claude 프로젝트 기능 활용법",
      "Claude로 장문 글쓰기 하는 방법",
      "Claude로 보고서 작성하는 방법",
      "Claude로 블로그 글 작성하는 방법",
      "Claude로 사업계획서 작성하는 방법",
      "Claude로 문서 요약하는 방법",
      "Claude로 계약서 초안 검토하는 방법",
      "Claude로 리서치 자료 정리하는 방법",
      "Claude 프롬프트 작성법",
      "Claude API 사용법 입문",
      "Claude 코딩 활용법",
      "Claude와 Notion 조합 활용법",
      "Claude로 책 원고 작성하는 방법",
      "Claude로 콘텐츠 시리즈 기획하는 방법",
      "Claude의 장점과 단점 총정리",
      "2026 Claude 최신 기능 정리",
      "Claude를 업무 비서로 사용하는 방법",
      "Claude로 회의록 정리하는 방법",
      "Claude로 이메일 작성하는 방법",
      "Claude로 브랜드 메시지 만드는 방법",
      "Claude로 고객 응대 문안 만드는 방법",
      "Claude로 교육 콘텐츠 만드는 방법",
      "Claude로 자기소개서 작성하는 방법",
      "Claude로 마케팅 카피 작성하는 방법",
      "Claude를 배워야 하는 이유",
      "Claude 사용 시 주의할 점",
    ],
    [1, 3, 5, 19]
  ),

  ...makeSeries(
    "ai-agents",
    "ai-agents",
    [
      "AI 에이전트란 무엇인가? 초보자 완벽 가이드",
      "AI 에이전트 시대가 온다",
      "AI 에이전트와 챗봇의 차이",
      "개인용 AI 비서 만드는 방법",
      "업무용 AI 에이전트 활용 사례",
      "AI 직원 만들기 가능할까?",
      "AI 에이전트로 자동화 시스템 구축하기",
      "OpenAI 에이전트 활용법",
      "Claude 기반 AI 에이전트 활용법",
      "Gemini 기반 AI 에이전트 활용법",
      "AI 에이전트 추천 툴 TOP 10",
      "AI 에이전트가 바꾸는 직업의 미래",
      "AI 에이전트로 콘텐츠 제작 자동화하기",
      "AI 에이전트로 고객 응대 자동화하기",
      "AI 에이전트로 리서치 자동화하기",
      "AI 에이전트로 블로그 운영하는 방법",
      "AI 에이전트로 쇼츠 기획하는 방법",
      "AI 에이전트와 n8n 연결 방법",
      "AI 에이전트와 Zapier 연결 방법",
      "AI 에이전트 수익화 전략",
      "AI 에이전트 구축 전 알아야 할 개념",
      "AI 에이전트의 한계와 위험성",
      "2026 AI 에이전트 트렌드",
      "1인 기업을 위한 AI 에이전트 전략",
      "AI 에이전트로 SaaS 만드는 아이디어",
      "AI 에이전트와 업무 자동화 로드맵",
      "AI 에이전트 활용 직무별 사례",
      "AI 에이전트 도입 체크리스트",
      "AI 에이전트 프롬프트 설계법",
      "AI 에이전트 시장 전망",
    ],
    [1, 6, 11, 20]
  ),

  ...makeSeries(
    "ai-automation",
    "ai-automation",
    [
      "AI 자동화란 무엇인가? 초보자 가이드",
      "AI 자동화로 업무 시간을 줄이는 방법",
      "n8n으로 AI 자동화 구축하기",
      "Make로 AI 자동화 만드는 방법",
      "Zapier와 ChatGPT 자동화 활용법",
      "AI 자동화로 블로그 운영하는 방법",
      "AI 자동화로 뉴스레터 만드는 방법",
      "AI 자동화로 SNS 콘텐츠 예약하기",
      "AI 자동화로 고객 응대 시스템 만들기",
      "AI 자동화로 리서치 자료 수집하기",
      "AI 자동화로 유튜브 대본 생성하기",
      "AI 자동화로 쇼츠 아이디어 생성하기",
      "AI 자동화로 콘텐츠 캘린더 만드는 방법",
      "AI 자동화로 이메일 답변 초안 만들기",
      "AI 자동화로 회의록 정리하기",
      "AI 자동화로 상품 설명문 생성하기",
      "AI 자동화로 SEO 키워드 분석하기",
      "AI 자동화로 보고서 자동 생성하기",
      "AI 자동화로 1인 기업 운영하기",
      "AI 자동화 수익화 아이디어",
      "AI 자동화 도입 전 체크리스트",
      "AI 자동화에 필요한 툴 TOP 10",
      "AI 자동화와 RPA 차이점",
      "AI 자동화 실패 사례와 해결 방법",
      "AI 자동화 워크플로우 설계법",
      "AI 자동화로 반복 업무 없애는 방법",
      "AI 자동화와 Google Sheets 연결하기",
      "AI 자동화와 Supabase 연결하기",
      "AI 자동화와 Slack 연결하기",
      "2026 AI 자동화 트렌드",
    ],
    [1, 3, 6, 20]
  ),

  ...makeSeries(
    "ai-coding",
    "ai-coding",
    [
      "AI 코딩이란 무엇인가?",
      "ChatGPT로 코딩 공부하는 방법",
      "Codex 활용법 완벽 정리",
      "Cursor 사용법 입문 가이드",
      "AI 코딩 툴 비교 분석",
      "AI가 개발자를 대체할까?",
      "AI와 함께 Next.js 개발하는 방법",
      "AI와 함께 React 개발하는 방법",
      "AI와 함께 TypeScript 배우는 방법",
      "AI로 코드 리뷰하는 방법",
      "AI로 버그 찾는 방법",
      "AI로 리팩토링하는 방법",
      "AI로 Supabase 연동 코드 작성하기",
      "AI로 API 설계하는 방법",
      "AI로 데이터베이스 스키마 설계하기",
      "AI로 프론트엔드 컴포넌트 만드는 방법",
      "AI로 Tailwind UI 만드는 방법",
      "AI로 개발 문서 작성하는 방법",
      "AI 코딩 생산성 높이는 워크플로우",
      "AI 코딩 초보자가 주의할 점",
      "AI 코딩 툴 추천 TOP 10",
      "Codex와 Cursor 비교 분석",
      "AI 코딩으로 MVP 빠르게 만드는 방법",
      "AI 코딩으로 SaaS 개발하는 방법",
      "AI 코딩 시대 개발자의 생존 전략",
    ],
    [3, 4, 5, 23]
  ),

  ...makeSeries(
    "ai-image",
    "ai-image",
    [
      "AI 이미지 생성이란 무엇인가?",
      "무료 AI 이미지 생성 툴 추천",
      "Midjourney 사용법 완벽 가이드",
      "Stable Diffusion 사용법 입문",
      "Flux 이미지 생성 활용법",
      "AI 이미지 프롬프트 작성법",
      "블로그 썸네일을 AI로 만드는 방법",
      "유튜브 썸네일을 AI로 만드는 방법",
      "AI 이미지 상업적 사용 가능할까?",
      "AI 이미지 저작권 주의사항",
      "AI 이미지로 브랜드 콘텐츠 만드는 방법",
      "AI 이미지로 광고 소재 만드는 방법",
      "AI 이미지 생성 툴 비교 분석",
      "AI 이미지 프롬프트 예시 50선",
      "AI 이미지 생성 실패 줄이는 방법",
      "AI 이미지 스타일 지정 방법",
      "AI 이미지로 캐릭터 만드는 방법",
      "AI 이미지로 제품 콘셉트 만드는 방법",
      "AI 이미지로 포스터 디자인하는 방법",
      "2026 AI 이미지 생성 트렌드",
    ],
    [1, 2, 6, 7]
  ),

  ...makeSeries(
    "ai-video",
    "ai-video",
    [
      "AI 영상 생성이란 무엇인가?",
      "AI 영상 생성 툴 추천 TOP 10",
      "Kling AI 사용법 완벽 정리",
      "Veo 사용법과 활용 사례",
      "Runway AI 영상 제작 가이드",
      "Pika AI 영상 생성 활용법",
      "AI 영상 프롬프트 작성법",
      "AI로 쇼츠 영상 만드는 방법",
      "AI로 광고 영상 만드는 방법",
      "AI로 유튜브 인트로 만드는 방법",
      "AI 영상 생성 툴 비교 분석",
      "AI 영상 상업적 사용 시 주의사항",
      "AI 영상 제작 워크플로우",
      "AI 영상으로 제품 홍보하기",
      "AI 영상으로 교육 콘텐츠 만들기",
      "AI 영상으로 음악 비디오 만들기",
      "AI 영상 생성 실패 줄이는 방법",
      "AI 영상과 편집 툴 조합 활용법",
      "AI 영상 콘텐츠 수익화 전략",
      "2026 AI 영상 생성 트렌드",
    ],
    [1, 3, 7, 20]
  ),

  ...makeSeries(
    "ai-voice",
    "ai-voice",
    [
      "AI 음성 생성이란 무엇인가?",
      "AI 음성 생성 툴 추천",
      "ElevenLabs 사용법 완벽 가이드",
      "AI 더빙 제작 방법",
      "AI 성우 만드는 방법",
      "AI 보이스 클론 활용법",
      "AI 음성으로 유튜브 내레이션 만들기",
      "AI 음성으로 팟캐스트 만드는 방법",
      "AI 음성 상업적 사용 가능할까?",
      "AI 음성 저작권 주의사항",
      "AI 음성으로 오디오북 만드는 방법",
      "AI 음성으로 강의 콘텐츠 만드는 방법",
      "AI 음성으로 쇼츠 내레이션 만드는 방법",
      "AI 음성 툴 비교 분석",
      "AI 음성 품질 높이는 방법",
      "AI 음성과 영상 제작 워크플로우",
      "AI 음성 수익화 전략",
      "AI 음성 기술의 미래",
      "AI 음성 생성 실패 줄이는 방법",
      "2026 AI 음성 트렌드",
    ],
    [1, 3, 7]
  ),

  ...makeSeries(
    "prompt-engineering",
    "prompt-engineering",
    [
      "프롬프트 엔지니어링이란 무엇인가?",
      "좋은 프롬프트 작성법 완벽 정리",
      "ChatGPT 프롬프트 예시 100선",
      "Gemini 프롬프트 작성법",
      "Claude 프롬프트 작성법",
      "블로그 글쓰기 프롬프트 모음",
      "마케팅 프롬프트 모음",
      "개발자 프롬프트 모음",
      "SEO 콘텐츠 프롬프트 작성법",
      "유튜브 대본 프롬프트 작성법",
      "AI 이미지 프롬프트 작성법",
      "AI 영상 프롬프트 작성법",
      "프롬프트 템플릿 만드는 방법",
      "프롬프트 자동화 워크플로우",
      "프롬프트 실패 사례와 개선법",
      "역할 부여 프롬프트 활용법",
      "체인 오브 생각 프롬프트 개념",
      "업무용 프롬프트 BEST 50",
      "프롬프트 엔지니어링을 배워야 하는 이유",
      "2026 프롬프트 엔지니어링 트렌드",
    ],
    [1, 2, 3, 19]
  ),

  ...makeSeries(
    "openai",
    "openai",
    [
      "OpenAI란 어떤 회사인가?",
      "OpenAI 기업 분석",
      "OpenAI 비즈니스 모델 분석",
      "OpenAI API 사용법 입문",
      "OpenAI와 Google AI 경쟁 분석",
      "OpenAI와 Anthropic 경쟁 분석",
      "OpenAI 수익 구조 분석",
      "OpenAI 최신 뉴스 정리",
      "OpenAI 모델 변천사",
      "GPT 모델 역사 총정리",
      "OpenAI API 비용 구조 이해하기",
      "OpenAI를 활용한 SaaS 아이디어",
      "OpenAI 생태계 분석",
      "OpenAI 투자 가치 분석",
      "OpenAI가 바꾸는 AI 산업",
      "OpenAI 개발자 도구 활용법",
      "OpenAI API로 챗봇 만드는 방법",
      "OpenAI API로 콘텐츠 생성기 만드는 방법",
      "OpenAI의 미래 전망",
      "2026 OpenAI 핵심 이슈 정리",
    ],
    [1, 2, 4, 20]
  ),

  ...makeSeries(
    "generative-ai",
    "generative-ai",
    [
      "생성형 AI란 무엇인가?",
      "생성형 AI 활용 사례 총정리",
      "생성형 AI가 바꾸는 직업의 미래",
      "생성형 AI와 콘텐츠 산업 변화",
      "생성형 AI와 교육의 미래",
      "생성형 AI와 마케팅 자동화",
      "생성형 AI와 1인 기업",
      "생성형 AI 수익화 전략",
      "생성형 AI 도구 추천 TOP 10",
      "생성형 AI 도입 전 알아야 할 점",
      "생성형 AI의 장점과 단점",
      "생성형 AI 저작권 이슈 정리",
      "생성형 AI와 검색엔진 변화",
      "생성형 AI와 블로그 SEO",
      "생성형 AI와 유튜브 콘텐츠 제작",
      "생성형 AI와 이미지 제작",
      "생성형 AI와 영상 제작",
      "생성형 AI와 음성 제작",
      "생성형 AI 시장 전망",
      "2026 생성형 AI 트렌드",
    ],
    [1, 2, 8, 20]
  ),

  ...makeSeries(
    "llm",
    "llm",
    [
      "LLM이란 무엇인가? 대규모 언어모델 입문",
      "LLM 작동 원리 쉽게 이해하기",
      "LLM과 생성형 AI의 차이",
      "LLM 모델 비교 분석",
      "오픈소스 LLM 추천",
      "LLM을 활용한 서비스 아이디어",
      "LLM API 사용 전 알아야 할 것",
      "LLM 파인튜닝이란 무엇인가?",
      "RAG란 무엇인가? 초보자 가이드",
      "LLM과 벡터 데이터베이스 이해하기",
      "LLM 기반 챗봇 만드는 방법",
      "LLM 기반 검색 시스템 만들기",
      "LLM의 한계와 환각 문제",
      "LLM 보안 이슈 정리",
      "LLM 비용 절감 전략",
      "LLM과 기업 업무 자동화",
      "LLM과 지식관리 시스템",
      "LLM 스타트업 아이디어",
      "LLM 시장 전망",
      "2026 LLM 트렌드",
    ],
    [1, 8, 9, 20]
  ),
];