-- =====================================================
-- CreAibox Music Album Plans DB Final
-- =====================================================

create table if not exists public.music_album_plans (
id uuid default gen_random_uuid() primary key,

display_id bigint generated by default as identity,

created_at timestamptz default timezone('utc', now()) not null,
updated_at timestamptz default timezone('utc', now()) not null,

user_id uuid references auth.users(id) on delete cascade not null,
user_email text,
user_nicename text,

title text,
description text,

genre text,
mood text,

concept text,
target_audience text,

target_song_count integer default 5,

language text default 'Korean',

vocal_direction text,
sound_direction text,

cover_concept text,
youtube_concept text,

track_list jsonb default '[]'::jsonb,

reference_keywords text[] default '{}',

related_album_id uuid
references public.music_albums(id)
on delete set null,

status text default 'saved',

is_favorite boolean default false,

raw_result jsonb
);

-- =====================================================
-- Indexes
-- =====================================================

create unique index if not exists idx_music_album_plans_display_id
on public.music_album_plans(display_id);

create index if not exists idx_music_album_plans_user_id
on public.music_album_plans(user_id);

create index if not exists idx_music_album_plans_created_at
on public.music_album_plans(created_at desc);

create index if not exists idx_music_album_plans_status
on public.music_album_plans(status);

create index if not exists idx_music_album_plans_favorite
on public.music_album_plans(is_favorite);

create index if not exists idx_music_album_plans_related_album_id
on public.music_album_plans(related_album_id);

-- =====================================================
-- updated_at Trigger
-- =====================================================

create or replace function public.set_music_album_plans_updated_at()
returns trigger as $$
begin
new.updated_at = timezone('utc', now());
return new;
end;
$$ language plpgsql;

drop trigger if exists set_music_album_plans_updated_at
on public.music_album_plans;

create trigger set_music_album_plans_updated_at
before update on public.music_album_plans
for each row
execute function public.set_music_album_plans_updated_at();

-- =====================================================
-- RLS
-- =====================================================

alter table public.music_album_plans
enable row level security;

drop policy if exists "사용자는 본인의 앨범 기획만 읽을 수 있습니다"
on public.music_album_plans;

drop policy if exists "사용자는 본인의 앨범 기획만 삽입할 수 있습니다"
on public.music_album_plans;

drop policy if exists "사용자는 본인의 앨범 기획만 수정할 수 있습니다"
on public.music_album_plans;

drop policy if exists "사용자는 본인의 앨범 기획만 삭제할 수 있습니다"
on public.music_album_plans;

create policy "사용자는 본인의 앨범 기획만 읽을 수 있습니다"
on public.music_album_plans
for select
using (
auth.uid() = user_id
);

create policy "사용자는 본인의 앨범 기획만 삽입할 수 있습니다"
on public.music_album_plans
for insert
with check (
auth.uid() = user_id
);

create policy "사용자는 본인의 앨범 기획만 수정할 수 있습니다"
on public.music_album_plans
for update
using (
auth.uid() = user_id
)
with check (
auth.uid() = user_id
);

create policy "사용자는 본인의 앨범 기획만 삭제할 수 있습니다"
on public.music_album_plans
for delete
using (
auth.uid() = user_id
);
