-- =====================================================
-- CreAibox Music Studio DB Final
-- =====================================================

-- 1. Generation Batch
create table if not exists public.music_generation_batches (
id uuid default gen_random_uuid() primary key,

display_id bigint generated by default as identity,

created_at timestamptz default timezone('utc', now()) not null,
updated_at timestamptz default timezone('utc', now()) not null,

user_id uuid references auth.users(id) on delete cascade not null,
user_email text,
user_nicename text,

theme text,
genre text,
mood text,
vocal text,
tempo text,
instrument text,
language text,
structure text,

concept_description text,

generation_count int default 1,

model_name text default 'gemini-3-flash-preview',

status text default 'saved',

raw_request jsonb
);

-- 2. Song Projects
create table if not exists public.music_lyrics_projects (
id uuid default gen_random_uuid() primary key,

display_id bigint generated by default as identity,

created_at timestamptz default timezone('utc', now()) not null,
updated_at timestamptz default timezone('utc', now()) not null,

batch_id uuid
references public.music_generation_batches(id)
on delete set null,

song_index int default 1,

user_id uuid references auth.users(id) on delete cascade not null,
user_email text,
user_nicename text,

title text,

theme text,

lyrics text,
translated_lyrics text,

suno_prompt text,

status text default 'saved',

genre text,
mood text,
vocal text,
tempo text,
instrument text,
language text,
structure text,

concept_description text,

youtube_titles jsonb default '[]'::jsonb,
youtube_description text,

hashtags jsonb default '[]'::jsonb,

cover_prompt text,
video_prompt text,

playlist_group text,
album_name text,

raw_result jsonb,

model_name text default 'gemini-3-flash-preview',

source_mode text default 'lyrics_suno',

is_favorite boolean default false
);

-- =====================================================
-- Indexes
-- =====================================================

create unique index if not exists idx_music_generation_batches_display_id
on public.music_generation_batches(display_id);

create index if not exists idx_music_generation_batches_user_id
on public.music_generation_batches(user_id);

create index if not exists idx_music_generation_batches_created_at
on public.music_generation_batches(created_at desc);

create unique index if not exists idx_music_lyrics_projects_display_id
on public.music_lyrics_projects(display_id);

create index if not exists idx_music_lyrics_projects_user_id
on public.music_lyrics_projects(user_id);

create index if not exists idx_music_lyrics_projects_batch_id
on public.music_lyrics_projects(batch_id);

create index if not exists idx_music_lyrics_projects_created_at
on public.music_lyrics_projects(created_at desc);

create index if not exists idx_music_lyrics_projects_status
on public.music_lyrics_projects(status);

create index if not exists idx_music_lyrics_projects_genre
on public.music_lyrics_projects(genre);

create index if not exists idx_music_lyrics_projects_favorite
on public.music_lyrics_projects(is_favorite);

-- =====================================================
-- updated_at Trigger
-- =====================================================

create or replace function public.set_updated_at()
returns trigger as $$
begin
new.updated_at = timezone('utc', now());
return new;
end;
$$ language plpgsql;

drop trigger if exists set_music_generation_batches_updated_at
on public.music_generation_batches;

create trigger set_music_generation_batches_updated_at
before update on public.music_generation_batches
for each row
execute function public.set_updated_at();

drop trigger if exists set_music_lyrics_projects_updated_at
on public.music_lyrics_projects;

create trigger set_music_lyrics_projects_updated_at
before update on public.music_lyrics_projects
for each row
execute function public.set_updated_at();

-- =====================================================
-- RLS
-- =====================================================

alter table public.music_generation_batches enable row level security;
alter table public.music_lyrics_projects enable row level security;

create policy "Users can read own music batches"
on public.music_generation_batches
for select
using (auth.uid() = user_id);

create policy "Users can insert own music batches"
on public.music_generation_batches
for insert
with check (auth.uid() = user_id);

create policy "Users can update own music batches"
on public.music_generation_batches
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own music batches"
on public.music_generation_batches
for delete
using (auth.uid() = user_id);

create policy "Users can read own music projects"
on public.music_lyrics_projects
for select
using (auth.uid() = user_id);

create policy "Users can insert own music projects"
on public.music_lyrics_projects
for insert
with check (auth.uid() = user_id);

create policy "Users can update own music projects"
on public.music_lyrics_projects
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own music projects"
on public.music_lyrics_projects
for delete
using (auth.uid() = user_id);
