-- =====================================================
-- CreAibox Music Albums DB Final
-- =====================================================

-- 1. Albums
create table if not exists public.music_albums (
id uuid default gen_random_uuid() primary key,

display_id bigint generated by default as identity,

created_at timestamptz default timezone('utc', now()) not null,
updated_at timestamptz default timezone('utc', now()) not null,

user_id uuid references auth.users(id) on delete cascade not null,
user_email text,
user_nicename text,

title text not null,
description text,

genre text,
mood text,

cover_image_url text,

status text default 'saved',

is_favorite boolean default false
);

-- =====================================================
-- Relationship
-- =====================================================

alter table public.music_lyrics_projects
add column if not exists album_id uuid
references public.music_albums(id)
on delete set null;

alter table public.music_lyrics_projects
add column if not exists album_name text;

-- =====================================================
-- Indexes
-- =====================================================

create unique index if not exists idx_music_albums_display_id
on public.music_albums(display_id);

create index if not exists idx_music_albums_user_id
on public.music_albums(user_id);

create index if not exists idx_music_albums_created_at
on public.music_albums(created_at desc);

create index if not exists idx_music_albums_favorite
on public.music_albums(is_favorite);

create index if not exists idx_music_albums_status
on public.music_albums(status);

create index if not exists idx_music_lyrics_projects_album_id
on public.music_lyrics_projects(album_id);

-- =====================================================
-- updated_at Trigger
-- =====================================================

create or replace function public.set_music_albums_updated_at()
returns trigger as $$
begin
new.updated_at = timezone('utc', now());
return new;
end;
$$ language plpgsql;

drop trigger if exists set_music_albums_updated_at
on public.music_albums;

create trigger set_music_albums_updated_at
before update on public.music_albums
for each row
execute function public.set_music_albums_updated_at();

-- =====================================================
-- RLS
-- =====================================================

alter table public.music_albums
enable row level security;

drop policy if exists "사용자는 본인의 음악 앨범만 읽을 수 있습니다"
on public.music_albums;

drop policy if exists "사용자는 본인의 음악 앨범만 삽입할 수 있습니다"
on public.music_albums;

drop policy if exists "사용자는 본인의 음악 앨범만 수정할 수 있습니다"
on public.music_albums;

drop policy if exists "사용자는 본인의 음악 앨범만 삭제할 수 있습니다"
on public.music_albums;

create policy "사용자는 본인의 음악 앨범만 읽을 수 있습니다"
on public.music_albums
for select
using (
auth.uid() = user_id
);

create policy "사용자는 본인의 음악 앨범만 삽입할 수 있습니다"
on public.music_albums
for insert
with check (
auth.uid() = user_id
);

create policy "사용자는 본인의 음악 앨범만 수정할 수 있습니다"
on public.music_albums
for update
using (
auth.uid() = user_id
)
with check (
auth.uid() = user_id
);

create policy "사용자는 본인의 음악 앨범만 삭제할 수 있습니다"
on public.music_albums
for delete
using (
auth.uid() = user_id
);
