-- =====================================================
-- CreAibox Writing Posts DB Final
-- =====================================================

create table if not exists public.writing_creaibox_posts (
id uuid default gen_random_uuid() primary key,

display_id bigint generated by default as identity,

created_at timestamptz default timezone('utc', now()) not null,
updated_at timestamptz default now(),

user_id uuid not null
references auth.users(id)
on delete cascade,

user_nicename text,

-- Content
title text,
content text,

target_keyword text,
selected_tone text,

post_type text default 'AI 인사이트 포스팅',

status text default 'saved',

-- SEO
slug text,
meta_description text,
focus_keyword text,
canonical_url text,
seo_tags text[],
category_id uuid references public.blog_categories(id) on delete set null,
toc_enabled boolean default true,

-- Settings
word_count_goal text,
source_mode text,
use_search boolean default true
);

-- =====================================================
-- Indexes
-- =====================================================

create index if not exists idx_writing_creaibox_posts_user_id
on public.writing_creaibox_posts(user_id);

create unique index if not exists idx_writing_creaibox_posts_display_id
on public.writing_creaibox_posts(display_id);

create index if not exists idx_writing_creaibox_posts_status
on public.writing_creaibox_posts(status);

create index if not exists idx_writing_creaibox_posts_slug
on public.writing_creaibox_posts(slug);

create index if not exists idx_writing_creaibox_posts_updated_at
on public.writing_creaibox_posts(updated_at desc);

-- =====================================================
-- updated_at Trigger
-- =====================================================

create or replace function public.set_updated_at()
returns trigger as $$
begin
new.updated_at = now();
return new;
end;
$$ language plpgsql;

drop trigger if exists set_writing_creaibox_posts_updated_at
on public.writing_creaibox_posts;

create trigger set_writing_creaibox_posts_updated_at
before update on public.writing_creaibox_posts
for each row
execute function public.set_updated_at();

-- =====================================================
-- RLS
-- =====================================================

alter table public.writing_creaibox_posts
enable row level security;

drop policy if exists
"사용자는 본인의 게시물만 읽을 수 있습니다"
on public.writing_creaibox_posts;

create policy
"사용자는 본인의 게시물만 읽을 수 있습니다"
on public.writing_creaibox_posts
for select
using (
auth.uid() = user_id
);

drop policy if exists
"사용자는 본인의 게시물만 삽입할 수 있습니다"
on public.writing_creaibox_posts;

create policy
"사용자는 본인의 게시물만 삽입할 수 있습니다"
on public.writing_creaibox_posts
for insert
with check (
auth.uid() = user_id
);

drop policy if exists
"사용자는 본인의 게시물만 수정할 수 있습니다"
on public.writing_creaibox_posts;

create policy
"사용자는 본인의 게시물만 수정할 수 있습니다"
on public.writing_creaibox_posts
for update
using (
auth.uid() = user_id
);

drop policy if exists
"사용자는 본인의 게시물만 삭제할 수 있습니다"
on public.writing_creaibox_posts;

create policy
"사용자는 본인의 게시물만 삭제할 수 있습니다"
on public.writing_creaibox_posts
for delete
using (
auth.uid() = user_id
);
