-- =====================================================
-- CreAibox Writing Naver Posts DB Final
-- =====================================================

create table if not exists public.writing_naver_posts (
id bigint generated by default as identity primary key,

user_id uuid not null
references auth.users(id)
on delete cascade,

user_email text not null default '',
user_nicename text not null default '',

title text not null default '제목 없음',
content text not null default '',

categories text[] not null default '{}',
tags text[] not null default '{}',

post_type text not null default 'smart'
check (post_type in ('smart', 'recreate')),

status text not null default 'draft'
check (status in ('draft', 'saved', 'published')),

target_keyword text,

source_url text,
source_text text,

rewrite_strategy text,

source_mode text,
selected_tone text,

word_count_goal integer,

created_at timestamptz default timezone('utc', now()) not null,
updated_at timestamptz default timezone('utc', now()) not null
);

-- =====================================================
-- Indexes
-- =====================================================

create index if not exists idx_naver_posts_user_id
on public.writing_naver_posts(user_id);

create index if not exists idx_naver_posts_user_email
on public.writing_naver_posts(user_email);

create index if not exists idx_naver_posts_post_type
on public.writing_naver_posts(post_type);

create index if not exists idx_writing_naver_posts_user_id_updated_at
on public.writing_naver_posts(user_id, updated_at desc);

create index if not exists idx_writing_naver_posts_target_keyword
on public.writing_naver_posts(target_keyword);

-- =====================================================
-- RLS
-- =====================================================

alter table public.writing_naver_posts
enable row level security;

drop policy if exists
"유저는 본인의 원고만 조회 가능합니다."
on public.writing_naver_posts;

create policy
"유저는 본인의 원고만 조회 가능합니다."
on public.writing_naver_posts
for select
to authenticated
using (
auth.uid() = user_id
);

drop policy if exists
"유저는 본인의 명의로만 원고 작성이 가능합니다."
on public.writing_naver_posts;

create policy
"유저는 본인의 명의로만 원고 작성이 가능합니다."
on public.writing_naver_posts
for insert
to authenticated
with check (
auth.uid() = user_id
);

drop policy if exists
"유저는 본인의 원고만 수정이 가능합니다."
on public.writing_naver_posts;

create policy
"유저는 본인의 원고만 수정이 가능합니다."
on public.writing_naver_posts
for update
to authenticated
using (
auth.uid() = user_id
)
with check (
auth.uid() = user_id
);

drop policy if exists
"유저는 본인의 원고만 삭제가 가능합니다."
on public.writing_naver_posts;

create policy
"유저는 본인의 원고만 삭제가 가능합니다."
on public.writing_naver_posts
for delete
to authenticated
using (
auth.uid() = user_id
);

-- =====================================================
-- updated_at Trigger
-- =====================================================

create or replace function update_writing_naver_posts_updated_at()
returns trigger as $$
begin
new.updated_at = now();
return new;
end;
$$ language plpgsql;

drop trigger if exists
trg_writing_naver_posts_updated_at
on public.writing_naver_posts;

create trigger trg_writing_naver_posts_updated_at
before update on public.writing_naver_posts
for each row
execute function update_writing_naver_posts_updated_at();
