import type { LyricsHubTemplate } from "../types";

export const acousticFolkTemplates: LyricsHubTemplate[] = [
  {
    id: "sunlight-bedroom-song",
    title: "방구석 토크 (Cozy Corner Song)",
    categoryId: "acoustic-folk",
    subTopicId: "cozy-room",
    mood: "잔잔한",
    vocal: "여성 솔로",
    instrument: "기타",
    tempo: "70-85 BPM",
    keywords: ["기타", "침대", "햇살", "커피"],
    description: "아침 햇살이 비치는 침대 옆에서 어쿠스틱 기타를 튕기며 부르는 포근하고 기분 좋은 고백.",
    lyricsBackground: "어깨에 닿는 따스한 햇빛과 향기로운 모닝커피를 마주하며, 헝클어진 머리도 사랑스러워 보이는 연인과의 소소한 일상을 편안한 어쿠스틱 기타 한 대와 나지막한 보컬로 표현.",
    placeSetting: "하얀 커튼 사이로 햇빛이 부서져 내리는 침대 옆 구석",
  },
  {
    id: "forest-wind-walking",
    title: "숲길의 휘파람 (Whistle in the Forest)",
    categoryId: "acoustic-folk",
    subTopicId: "nature-walk",
    mood: "잔잔한",
    vocal: "남성 솔로",
    instrument: "기타",
    tempo: "80-95 BPM",
    keywords: ["바람", "숲길", "낙엽", "산책"],
    description: "바람 부는 가을 숲길을 걸으며 낙엽 밟는 소리와 함께 옛 소중했던 대화들을 회상하는 노래.",
    lyricsBackground: "사각사각 낙엽 밟히는 소리와 살랑이는 숲속 바람을 멜로디 삼아, 잊고 살았던 순수했던 시절의 마음과 소박한 꿈들을 서정적인 퍼커션과 통기타 아르페지오 사운드에 담아냄.",
    placeSetting: "울긋불긋 단풍이 내려앉은 조용한 숲속 산책로",
  },
  {
    id: "rainy-window-sketch",
    title: "비 오는 날의 스케치 (Rainy Sketch)",
    categoryId: "acoustic-folk",
    subTopicId: "cozy-room",
    mood: "잔잔한",
    vocal: "듀엣",
    instrument: "기타",
    tempo: "65-80 BPM",
    keywords: ["빗방울", "창문", "찻잔", "기억"],
    description: "창문에 맺히는 물방울을 보며 따뜻한 차 한 잔을 앞에 두고 조용히 옛 기억을 꺼내 놓는 듀엣곡.",
    lyricsBackground: "소박한 기타 선율과 감미로운 혼성 듀엣 보컬이 마치 대화를 나누듯 편안하게 조화를 이룸. 비 오는 오후의 정적과 나른함을 어쿠스틱 포크 특유의 빈티지한 감성으로 재현.",
    placeSetting: "비가 주룩주룩 내리는 오후, 김이 서린 창가 테이블",
  },
  {
    id: "campfire-traveler",
    title: "모닥불과 낡은 기타 (Campfire & Old Guitar)",
    categoryId: "acoustic-folk",
    subTopicId: "nature-walk",
    mood: "잔잔한",
    vocal: "남성 솔로",
    instrument: "기타",
    tempo: "75-90 BPM",
    keywords: ["모닥불", "별빛", "텐트", "밤하늘"],
    description: "캠핑장 모닥불 앞에서 별빛 가득한 하늘을 보며 친구들과 청춘의 우정과 내일을 노래하는 곡.",
    lyricsBackground: "탁탁 튀는 모닥불 소리와 붉게 피어오르는 불꽃을 보며, 바쁜 일상에 잠시 쉼표를 찍고 자연의 위로 속에서 마음의 치유를 얻는 내추럴 포크 송.",
    placeSetting: "풀벌레 소리 들리는 호숫가 옆 텐트와 모닥불 앞",
  },
  {
    id: "bookshelf-cat-lazy",
    title: "책장 위의 고양이처럼 (Like a Lazy Cat)",
    categoryId: "acoustic-folk",
    subTopicId: "cozy-room",
    mood: "잔잔한",
    vocal: "여성 솔로",
    instrument: "기타",
    tempo: "80-95 BPM",
    keywords: ["고양이", "낮잠", "만화책", "나른함"],
    description: "나른한 오후, 책장 위에 올라가 하품하는 고양이를 보며 아무 생각 없이 쉬고 싶은 날의 가사.",
    lyricsBackground: "어쿠스틱 우쿨렐레와 나일론 기타 사운드가 통통 튀며, 바쁜 현대 사회의 타임라인에서 벗어나 오롯이 나만의 빈둥거림을 예찬하는 가볍고 사랑스러운 어쿠스틱 팝.",
    placeSetting: "오래된 만화책들이 가득 꽂힌 나른한 다락방",
  },
  {
    id: "sea-breeze-stroll",
    title: "바람과 모래언덕 (Sea Breeze Stroll)",
    categoryId: "acoustic-folk",
    subTopicId: "nature-walk",
    mood: "잔잔한",
    vocal: "듀엣",
    instrument: "기타",
    tempo: "85-100 BPM",
    keywords: ["바닷가", "파도", "모래언덕", "맨발"],
    description: "한적한 동해바다 모래사장 위를 맨발로 걸으며 차가운 바닷바람과 파도 소리를 즐기는 힐링곡.",
    lyricsBackground: "밀려왔다 밀려가는 파도 거품을 보며, 묵혀두었던 갈등과 상처를 모두 바다에 흘려보낸다. 맑은 어쿠스틱 스틸 기타 스트로크와 허밍 사운드가 드넓은 바다의 청량함을 돋보이게 함.",
    placeSetting: "사람이 많지 않은 늦가을의 해질녘 바닷가",
  },
];
