import type { LyricsHubTemplate } from "../types";

export const balladTemplates: LyricsHubTemplate[] = [
  {
    id: "midnight-tear",
    title: "자정의 혼잣말 (Midnight Monologue)",
    categoryId: "ballad",
    subTopicId: "sad-dawn",
    mood: "애절한",
    vocal: "여성 솔로",
    instrument: "피아노",
    tempo: "60-80 BPM",
    keywords: ["새벽", "외로움", "침묵", "기억"],
    description: "아무도 없는 깊은 밤, 방 안에서 흘러나오는 라디오 소리를 들으며 혼자 읊조리는 이별의 잔상.",
    lyricsBackground: "어두운 방, 홀로 불을 끄고 누워 천장을 바라보며 마지막 통화의 음성을 되짚어보는 화자의 마음을 애절한 피아노 선율과 현악 오케스트레이션으로 표현.",
    placeSetting: "어두운 자정의 방 안",
  },
  {
    id: "rainy-bus-stop",
    title: "빗속의 버스 정류장 (Bus Stop in the Rain)",
    categoryId: "ballad",
    subTopicId: "tearful-rain",
    mood: "쓸쓸한",
    vocal: "남성 솔로",
    instrument: "어쿠스틱 피아노",
    tempo: "70-85 BPM",
    keywords: ["우산", "정류장", "버스", "빗소리"],
    description: "갑자기 쏟아지는 비를 피하며, 우산이 없어 비를 맞고 가던 그날의 너를 떠올리는 이야기.",
    lyricsBackground: "버스 정류장에서 창밖을 보며 흐르는 눈물과 떨어지는 빗방울을 동일시하며, 미처 잡지 못했던 인연에 대한 후회를 웅장한 스트링과 어쿠스틱 피아노 사운드로 묘사.",
    placeSetting: "비 내리는 저녁, 버스 정류장",
  },
  {
    id: "cold-coffee-regret",
    title: "식어버린 아메리카노 (Cold Americano)",
    categoryId: "ballad",
    subTopicId: "sad-dawn",
    mood: "잔잔한",
    vocal: "여성 솔로",
    instrument: "기타 & 피아노",
    tempo: "65-80 BPM",
    keywords: ["커피", "시간", "습관", "미련"],
    description: "카페 구석자리에서 마주 앉았던 흔적을 더듬으며, 식어버린 커피를 바라보는 슬픈 시선.",
    lyricsBackground: "시간이 흘러 식어버린 음료처럼, 차갑게 돌아서던 상대방의 마지막 눈빛과 건조했던 말투를 잔잔한 어쿠스틱 기타와 서정적인 피아노 멜로디에 실어 담아냄.",
    placeSetting: "추억이 깃든 동네 작은 카페",
  },
  {
    id: "last-letter-envelope",
    title: "보내지 못한 봉투 (Unsent Letter)",
    categoryId: "ballad",
    subTopicId: "sad-dawn",
    mood: "아련한",
    vocal: "남성 솔로",
    instrument: "스트링 & 피아노",
    tempo: "60-75 BPM",
    keywords: ["손편지", "우표", "서랍", "눈물자국"],
    description: "이별 후 써 내려갔지만 결국 주소를 적지 못한 채 서랍 깊숙이 묻어둔 편지에 관한 독백.",
    lyricsBackground: "글자마다 꾹꾹 눌러 담은 마음과 얼룩진 눈물 자국을 바라보며, 전하지 못한 안부가 가슴 아프게 울려 퍼지는 오케스트럴 발라드.",
    placeSetting: "책상 앞, 낡은 서랍 속",
  },
  {
    id: "street-lamp-shadow",
    title: "가로등 밑에서 울던 너 (Under the Street Lamp)",
    categoryId: "ballad",
    subTopicId: "tearful-rain",
    mood: "애절한",
    vocal: "듀엣",
    instrument: "피아노 & 스트링",
    tempo: "75-90 BPM",
    keywords: ["가로등", "그림자", "골목길", "포옹"],
    description: "집 앞 가로등 아래에서 눈물 흘리며 서로를 보낼 수밖에 없었던 마지막 밤의 약속.",
    lyricsBackground: "남녀의 어긋난 타이밍과 서글픈 상황을 주고받는 듀엣 구성으로, 가로등 불빛이 둘의 그림자를 길게 늘어뜨리듯 아련하고 깊은 울림을 주는 발라드.",
    placeSetting: "차가운 겨울 밤, 집 앞 가로등 밑",
  },
  {
    id: "first-snow-wish",
    title: "첫눈이 올 때쯤엔 (When the First Snow Falls)",
    categoryId: "ballad",
    subTopicId: "sad-dawn",
    mood: "아련한",
    vocal: "여성 솔로",
    instrument: "오르골 & 피아노",
    tempo: "65-80 BPM",
    keywords: ["첫눈", "겨울", "약속", "화이트"],
    description: "첫눈이 내리면 만나자던 지난날의 약속을 떠올리며 혼자 눈을 맞이하는 겨울 발라드.",
    lyricsBackground: "하늘에서 떨어지는 하얀 눈송이들을 보며, 그 겨울의 따뜻했던 품을 그리워하는 슬프지만 아름다운 멜로디. 오르골의 인트로와 웅장한 후렴구 현악기가 특징.",
    placeSetting: "첫눈이 내리는 회색빛 도심 거리",
  },
];
