import type { LyricsHubTemplate } from "../types";

export const cityPopTemplates: LyricsHubTemplate[] = [
  {
    id: "city-neon-express",
    title: "한밤의 네온 익스프레스 (Midnight Neon Express)",
    categoryId: "citypop",
    subTopicId: "midnight-drive",
    mood: "도시적인",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "110-130 BPM",
    keywords: ["네온사인", "가로등", "밤바람", "카라디오"],
    description: "밤 드라이브 중 스쳐 지나가는 네온사인과 도시의 화려함 뒤에 숨겨진 쓸쓸함을 회상하는 스토리.",
    lyricsBackground: "밤 12시 고속도로를 달리며 라디오에서 나오는 노래 소리에 흘러간 사랑을 실어 보내는 화자의 감정을 대변. 레트로 신스 사운드와 함께 속도감 있게 전개되는 애달픈 사랑 노래.",
    placeSetting: "도심 순환 고속도로, 밤 차 안",
  },
  {
    id: "sunset-rooftop",
    title: "노을빛 루프탑 (Sunset Rooftop)",
    categoryId: "citypop",
    subTopicId: "neon-lights",
    mood: "몽환적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "90-110 BPM",
    keywords: ["노을", "루프탑", "칵테일", "그림자"],
    description: "해질녘 빌딩숲 루프탑에서 칵테일 한 잔을 들고 옛 연인과의 아련한 추억을 회상하는 로맨틱 시티팝.",
    lyricsBackground: "붉게 물드는 빌딩숲 사이로 차가운 칵테일 잔을 잡고, 서로의 그림자가 포개지던 여름날의 어스름을 노래. 펑키한 베이스 리듬 위에 얹어지는 부드러운 하모니.",
    placeSetting: "도심 고층 빌딩 루프탑 카페",
  },
  {
    id: "telephone-line-love",
    title: "공중전화 박스의 자정 (Midnight Telephone Box)",
    categoryId: "citypop",
    subTopicId: "neon-lights",
    mood: "아련한",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "90-110 BPM",
    keywords: ["전화부스", "동전", "컬러링", "신호음"],
    description: "비 내리는 밤, 공중전화 박스 안에서 수화기를 들고 걸지 못할 번호를 누르는 레트로 감성의 가사.",
    lyricsBackground: "스마트폰이 없던 시절, 동전 몇 개를 쥐고 빗소리가 흐르는 전화부스 속에서 수화기 너머 신호음에 가슴 떨리던 추억을 80년대 특유의 아련한 시티팝 리듬으로 노래함.",
    placeSetting: "가로등 불빛 아래 낡은 공중전화 부스",
  },
  {
    id: "highway-night-breeze",
    title: "올림픽대로의 밤바람 (Olympic Highway Breeze)",
    categoryId: "citypop",
    subTopicId: "midnight-drive",
    mood: "도시적인",
    vocal: "듀엣",
    instrument: "신스",
    tempo: "110-130 BPM",
    keywords: ["올림픽대로", "한강", "헤드라이트", "스피커"],
    description: "창문을 활짝 열고 올림픽대로를 달리며 한강의 빛나는 불빛을 보며 청춘과 해방감을 노래하는 듀엣곡.",
    lyricsBackground: "지친 하루를 끝마친 남녀가 차를 타고 한강변을 달리며 차가운 밤바람에 걱정을 날려 보내고, 서로의 손을 잡으며 조용한 사랑을 확인하는 어반 시티팝.",
    placeSetting: "한강 가를 달리는 올림픽대로 차 안",
  },
  {
    id: "vinyl-record-cafe",
    title: "레코드판 카페의 구석자리 (Vinyl & Late Night Coffee)",
    categoryId: "citypop",
    subTopicId: "neon-lights",
    mood: "잔잔한",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "70-90 BPM",
    keywords: ["레코드판", "턴테이블", "커피", "낙서"],
    description: "골목길 구석 오래된 LP 바에서 흘러나오는 노래를 들으며 일기장을 적어 내려가는 잔잔한 템포의 가사.",
    lyricsBackground: "턴테이블 위 바늘이 긁히는 따뜻한 질감의 잡음 속에서, 지나간 겨울날 우리를 춤추게 했던 멜로디를 찾는다. 퓨전 재즈와 시티팝의 경계에 있는 그루비한 발라드.",
    placeSetting: "골목길에 숨겨진 오래된 레코드 LP 카페",
  },
  {
    id: "neon-heartbeat",
    title: "네온 심박수 (Neon Heartbeat)",
    categoryId: "citypop",
    subTopicId: "midnight-drive",
    mood: "몽환적인",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "110-130 BPM",
    keywords: ["심박수", "속도", "라이트", "스파크"],
    description: "질주하는 차의 속도에 맞춰 두근거리는 심장 소리를 시티팝 특유의 화려한 드럼과 신스웨이브로 표현.",
    lyricsBackground: "조금씩 빨라지는 도시의 밤바람과 너를 향한 내 감정의 기어. 주저하지 말고 액셀을 밟아 이 밤의 끝을 향해 가자는 에너제틱하고 트렌디한 시티팝 가사.",
    placeSetting: "불빛이 꼬리를 물고 이어지는 자정의 도심 도로",
  },
];
