import type { LyricsHubTemplate } from "../types";

export const edmDanceTemplates: LyricsHubTemplate[] = [
  {
    id: "neon-beach-party",
    title: "형광빛 모래사장 (Neon Sand & Summer Night)",
    categoryId: "edm-dance",
    subTopicId: "summer-festival",
    mood: "도시적인",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "120-135 BPM",
    keywords: ["해변", "페스티벌", "모래사장", "칵테일"],
    description: "한여름 밤 해변가에서 열리는 일렉트로닉 파티의 열기와 뜨거운 심장 소리를 담은 댄스곡.",
    lyricsBackground: "파도 소리와 베이스 비트가 하나로 뒤섞이는 밤, 모든 걱정을 모래사장에 묻어둔 채 음악에 맞춰 뛰어노는 청춘들의 짜릿하고 해방감 넘치는 가사.",
    placeSetting: "조명이 가득한 한여름 밤의 해변 축제 무대",
  },
  {
    id: "laser-beam-escape",
    title: "레이저 빔 속의 일탈 (Laser Beam Escape)",
    categoryId: "edm-dance",
    subTopicId: "club-energy",
    mood: "몽환적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "125-140 BPM",
    keywords: ["레이저", "베이스", "스피커", "탈출"],
    description: "현란하게 교차하는 레이저 불빛 아래에서 땀방울을 흘리며 일상의 무거운 규칙에서 도망치는 곡.",
    lyricsBackground: "사방으로 퍼지는 사이키델릭한 조명과 가슴을 때리는 웅장한 서브 베이스 속에서, 자유를 향해 손을 뻗는 역동적이고 세련된 EDM 댄스 스타일의 가사.",
    placeSetting: "스피커 진동이 온몸으로 느껴지는 어두운 클럽 센터",
  },
  {
    id: "fireworks-love-spark",
    title: "불꽃의 스파크 (Spark in the Sky)",
    categoryId: "edm-dance",
    subTopicId: "summer-festival",
    mood: "도시적인",
    vocal: "듀엣",
    instrument: "신스",
    tempo: "128 BPM",
    keywords: ["폭죽", "밤하늘", "스파크", "카운트다운"],
    description: "밤하늘을 화려하게 장식하는 폭죽 아래서 눈이 마주친 남녀의 짜릿한 순간을 노래하는 댄스 트랙.",
    lyricsBackground: "웅장한 페스티벌 무대, 드롭(Drop) 직전의 터질 듯한 빌드업과 함께 폭죽이 쏘아 올려지는 순간의 벅찬 감정과 연애의 시작을 일렉트로 하우스 비트로 표현.",
    placeSetting: "수만 명의 함성이 가득한 야외 락/EDM 페스티벌 광장",
  },
  {
    id: "weekend-midnight-drive",
    title: "주말 자정의 해방구 (Midnight Circuit)",
    categoryId: "edm-dance",
    subTopicId: "club-energy",
    mood: "도시적인",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "120-130 BPM",
    keywords: ["금요일", "탈출", "조명", "댄스플로어"],
    description: "금요일 밤 퇴근 직후 옷을 갈아입고 도심의 밤으로 뛰어드는 오피스 워커의 자유 찬가.",
    lyricsBackground: "타이와 격식을 던져버리고 일렉트릭 리듬에 몸을 맡겨, 월요일이 오지 않을 것처럼 춤추자는 메시지를 경쾌하고 퓨처 하우스 리듬 위에 얹어낸 가사.",
    placeSetting: "금요일 밤, 화려한 미러볼이 도는 플로어",
  },
  {
    id: "starlight-electro-flight",
    title: "스타라이트 플라이트 (Starlight Electro Flight)",
    categoryId: "edm-dance",
    subTopicId: "summer-festival",
    mood: "몽환적인",
    vocal: "듀엣",
    instrument: "신스",
    tempo: "124-128 BPM",
    keywords: ["비행", "은하수", "속도", "에너지"],
    description: "신디사이저 멜로디에 실려 은하수를 향해 날아가는 듯한 벅찬 에너지를 노래하는 멜로딕 다이내믹 댄스.",
    lyricsBackground: "중력을 벗어난 듯 붕 뜨는 신스 리듬과 보컬 찹(Vocal Chops)이 조화를 이루며, 무한한 우주 공간으로 단 둘만의 탈출을 감행하는 시원한 분위기의 업템포 트랙.",
    placeSetting: "가상의 일렉트로 우주 정거장 플로어",
  },
  {
    id: "bass-drop-heartbeat",
    title: "베이스 드롭 하트 (Bass Drop Heart)",
    categoryId: "edm-dance",
    subTopicId: "club-energy",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "130 BPM",
    keywords: ["드롭", "스파크", "진동", "샤우트"],
    description: "강렬한 비트 드롭과 함께 심장이 터질 것 같은 강한 끌림을 직설적으로 고백하는 하드코어 댄스 가사.",
    lyricsBackground: "거친 신스 라인과 심장을 관통하는 킥 사운드. 눈이 마주치는 순간 가로막고 있던 이성의 벽이 허물어지고 서로에게 올인하는 순간을 묘사함.",
    placeSetting: "어둡고 레이저 불빛이 번쩍이는 테크노 클럽 지하",
  },
];
