import type { LyricsHubTemplate } from "../types";

export const hiphopRapTemplates: LyricsHubTemplate[] = [
  {
    id: "asphalt-monologue",
    title: "아스팔트 위의 독백 (Asphalt Monologue)",
    categoryId: "hiphop-rap",
    subTopicId: "street-story",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "85-100 BPM",
    keywords: ["독백", "가로등", "아스팔트", "현실"],
    description: "새벽녘 가로등 불빛이 희미한 골목길을 걸으며, 성공을 향한 의지와 쓸쓸한 현실을 다지는 랩 트랙.",
    lyricsBackground: "어두운 밤, 편의점 파라솔 밑에 앉아 캔맥주를 마시며 세상에 던지는 무겁고 치열한 랩. 미니멀한 808 베이스와 로파이한 피아노 샘플 루프 위에 자전적인 이야기를 담음.",
    placeSetting: "차가운 새벽 공기가 흐르는 주택가 골목길 편의점 앞",
  },
  {
    id: "microphone-sweat",
    title: "마이크 위의 땀방울 (Sweat on the Mic)",
    categoryId: "hiphop-rap",
    subTopicId: "rough-dream",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "90-110 BPM",
    keywords: ["마이크", "지하", "열정", "가사지"],
    description: "창문 하나 없는 좁은 지하 작업실에서 먼지를 마시며 가사지를 적어 내려가는 래퍼의 다짐.",
    lyricsBackground: "지인들의 비아냥과 불확실한 미래에도 굴하지 않고 오직 목소리 하나로 증명해 보이겠다는 굳은 신념. 빠른 하이햇 연타와 타이트한 드럼 비트에 실린 강렬한 붐뱁 랩.",
    placeSetting: "방음 스펀지가 다 뜯어진 좁은 지하 연습실",
  },
  {
    id: "neon-lonely-express",
    title: "회색빛 택시의 뒷좌석 (Backseat of Grey Taxi)",
    categoryId: "hiphop-rap",
    subTopicId: "street-story",
    mood: "쓸쓸한",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "80-95 BPM",
    keywords: ["택시", "창창", "야경", "한숨"],
    description: "하루의 끝자락, 택시를 타고 한강 대교를 건너며 복잡한 마음을 풀어내는 싱잉 랩 가사.",
    lyricsBackground: "주르륵 흐르는 빗방울과 택시 창밖으로 빠르게 스쳐가는 가로등의 궤적을 보며, 잃어버린 꿈과 인간관계에 대한 피로를 감성적인 멜로디 랩으로 풀어낸 곡.",
    placeSetting: "한강 다리를 지나는 택시 뒷좌석",
  },
  {
    id: "concrete-jungle-dream",
    title: "콘크리트 정글의 꿈 (Concrete Dreamer)",
    categoryId: "hiphop-rap",
    subTopicId: "rough-dream",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "95-115 BPM",
    keywords: ["빌딩숲", "콘크리트", "질주", "미래"],
    description: "높이 솟아오른 고층 빌딩숲 사이를 걸으며, 언젠가 저 꼭대기 위에 내 이름을 새기겠다는 야망.",
    lyricsBackground: "현실의 벽은 높고 차갑지만, 결코 멈추지 않고 매 순간 한계를 뛰어넘겠다는 의지. 묵직하고 트렌디한 트랩 비트와 웅장한 신스 혼(Horn) 사운드가 폭발적인 조화를 이룸.",
    placeSetting: "거대한 빌딩들이 가득한 광화문 혹은 강남 대로 한복판",
  },
  {
    id: "vinyl-memory-groove",
    title: "오래된 LP와 일기장 (Old Vinyl & Journal)",
    categoryId: "hiphop-rap",
    subTopicId: "street-story",
    mood: "잔잔한",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "85-100 BPM",
    keywords: ["일기장", "추억", "노을", "연필"],
    description: "어릴 적 살던 동네 골목길을 걸으며 예전 꿈꾸던 꼬마였던 시절을 회상하는 힙합/알앤비 트랙.",
    lyricsBackground: "다 때 묻은 일기장을 한 장씩 넘기듯, 소박했지만 매 순간이 빛나던 옛 추억을 꺼내 본다. 재즈힙합 특유의 따뜻하고 편안한 리듬과 어쿠스틱 피아노 선율이 편안함을 선사함.",
    placeSetting: "어스름이 내리는 고향 동네 오래된 담벼락 앞",
  },
  {
    id: "hustle-caffeine-night",
    title: "카페인 밤샘 (Caffeine and Hustle)",
    categoryId: "hiphop-rap",
    subTopicId: "rough-dream",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "90-105 BPM",
    keywords: ["커피", "노트북", "야근", "성공"],
    description: "모두가 잠든 새벽, 커피 한 잔에 의지해 모니터 불빛 앞에서 미래를 창조해가는 청춘의 허슬.",
    lyricsBackground: "졸음과 싸우며 가사와 멜로디를 직조하는 크리에이터의 일상. 16비트의 쪼개지는 트랩 드럼과 몽환적인 신스 패드 사운드가 더해져 고독하면서도 몰입감 넘치는 가사 전개.",
    placeSetting: "컴퓨터 팬 소리만 조용히 들리는 자취방 책상 앞",
  },
];
