import type { LyricsHubTemplate } from "../types";

export const rnbSoulTemplates: LyricsHubTemplate[] = [
  {
    id: "jazz-lounge-whisper",
    title: "재즈 라운지의 자정 (Whisper at Jazz Lounge)",
    categoryId: "rnb-soul",
    subTopicId: "jazz-lounge",
    mood: "도시적인",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "80-95 BPM",
    keywords: ["재즈", "라운지", "와인", "속삭임"],
    description: "은은한 조명이 비추는 재즈 라운지 구석에서 달콤하고 비밀스러운 고백을 나누는 네오 소울 곡.",
    lyricsBackground: "더블 베이스와 Rhodes 피아노의 따뜻한 사운드 속에서, 얼음이 녹아내리는 유리잔을 만지며 조심스럽게 서로의 눈빛을 읽어 내리는 감미롭고 섹시한 가사.",
    placeSetting: "붉은 네온사인이 은은하게 흐르는 도심 재즈 클럽 바",
  },
  {
    id: "groovin-rainy-morning",
    title: "비 내리는 일요일 아침 (Sunday Morning Groovin')",
    categoryId: "rnb-soul",
    subTopicId: "sweet-confession",
    mood: "잔잔한",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "75-90 BPM",
    keywords: ["일요일", "침대", "lp", "속삭임"],
    description: "밖에 비가 내려도 이불 속에서 좋아하는 음악을 들으며 연인과 소박한 행복을 나누는 슬로우 잼.",
    lyricsBackground: "빗방울이 창문을 톡톡 치는 소리를 퍼커션 삼아, 따뜻한 담요 아래에서 들려오는 가벼운 숨소리와 사랑 고백을 레이백(Layback) 그루브에 실어 부드럽게 표현.",
    placeSetting: "비 내리는 주말 아침, 따스한 온기가 남은 침대 위",
  },
  {
    id: "candlelight-slow-dance",
    title: "촛불 아래 슬로우 댄스 (Candlelight & Slow Dance)",
    categoryId: "rnb-soul",
    subTopicId: "jazz-lounge",
    mood: "몽환적인",
    vocal: "듀엣",
    instrument: "신스",
    tempo: "70-85 BPM",
    keywords: ["촛불", "댄스", "그림자", "고백"],
    description: "방 안 가득 켠 촛불과 나른한 알앤비 음악 속에서 서로를 안고 조용히 춤추는 연인의 깊은 고백.",
    lyricsBackground: "시계 바늘 소리마저 느려지는 밤, 단 둘만을 위한 공간에서 서로의 온기에 의지해 어두운 그림자들을 겹치며 영원을 약속하는 슬로우 R&B 듀엣 송.",
    placeSetting: "조용한 자취방, 흔들리는 촛불들 사이",
  },
  {
    id: "rooftop-wine-talk",
    title: "와인과 옥탑방의 별빛 (Rooftop Wine & Stars)",
    categoryId: "rnb-soul",
    subTopicId: "sweet-confession",
    mood: "잔잔한",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "85-100 BPM",
    keywords: ["옥탑방", "와인", "별빛", "이야기"],
    description: "편안한 홈웨어를 입고 옥상에 올라 저렴한 와인을 마시며 미래의 꿈을 속삭이는 그루비한 알앤비.",
    lyricsBackground: "화려한 가구는 없지만 서로가 있어 가득 차 보이는 옥상 계단에 앉아, 차가운 밤공기 속에 서로의 볼을 비비며 영원할 것 같은 현재의 감정을 포근하게 노래함.",
    placeSetting: "도심 야경이 훤히 내려다보이는 작은 옥탑 평상",
  },
  {
    id: "velvet-night-drive",
    title: "벨벳 나이트 드라이브 (Velvet Night Drive)",
    categoryId: "rnb-soul",
    subTopicId: "jazz-lounge",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "90-105 BPM",
    keywords: ["헤드라이트", "가로등", "시티라이트", "베이스"],
    description: "어두워진 도심의 대로를 시원하게 미끄러져 가며 밤거리가 주는 고독과 낭만을 노래하는 R&B 트랙.",
    lyricsBackground: "묵직한 베이스 라인과 그루비한 신스 멜로디 위에, 도심 속 홀로 차를 타고 속도를 줄이며 혼자만의 사색과 자유로운 영혼을 노래하는 미디엄 템포 어반 소울.",
    placeSetting: "도심 가로등 아래를 주행하는 자동차 내부",
  },
  {
    id: "soulful-coffee-shop",
    title: "비엔나커피 한 잔의 소울 (Sweet Vienna Soul)",
    categoryId: "rnb-soul",
    subTopicId: "sweet-confession",
    mood: "잔잔한",
    vocal: "듀엣",
    instrument: "신스",
    tempo: "80-95 BPM",
    keywords: ["크림", "커피", "웃음", "달콤함"],
    description: "커피 위에 얹어진 하얀 크림처럼 부드럽고 달콤한 미소를 짓는 상대를 향한 소울풀한 연가.",
    lyricsBackground: "남녀의 달콤한 화음이 에스프레소와 크림의 조화처럼 어우러지며, 마주한 테이블 위로 오고 가는 따뜻한 장난과 깊어지는 눈빛을 위트 넘치게 묘사한 트렌디 R&B.",
    placeSetting: "레트로한 갈색 목재 가구들이 놓인 골목 커피숍",
  },
];
