import type { LyricsHubTemplate } from "../types";

export const rockMetalTemplates: LyricsHubTemplate[] = [
  {
    id: "garage-band-rebel",
    title: "차고지 밴드의 외침 (Garage Band Rebellion)",
    categoryId: "rock-metal",
    subTopicId: "youth-rebel",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "기타",
    tempo: "130-150 BPM",
    keywords: ["락밴드", "소리", "질주", "자유"],
    description: "먼지 가득한 차고지에서 이웃들의 소음 신고에도 굴하지 않고 앰프를 최대치로 올리고 청춘을 노래하는 곡.",
    lyricsBackground: "세상의 고정관념과 억압에 맞서, 일렉기타의 디스토션 사운드 위에 목이 터져라 지르는 강렬한 얼터너티브 락. 타격감 있는 드럼과 베이스 리프가 가슴을 울림.",
    placeSetting: "낡은 드럼 세트와 진공관 앰프가 늘어선 주택가 차고 안",
  },
  {
    id: "roaring-thunder-rage",
    title: "천둥의 심장박동 (Roaring Thunder)",
    categoryId: "rock-metal",
    subTopicId: "heavy-heart",
    mood: "애절한",
    vocal: "남성 솔로",
    instrument: "기타",
    tempo: "140-160 BPM",
    keywords: ["울분", "샤우팅", "일렉기타", "폭풍"],
    description: "가슴속에 응어리진 억압과 슬픔을 천둥처럼 포효하며 분출하는 메탈/하드락 트랙.",
    lyricsBackground: "폭풍우가 치는 밤하늘처럼, 분노와 슬픔이 혼재된 마음의 고통을 찢어지는 일렉기타 솔로와 스크리밍 보컬로 극대화하여 표현한 고에너지 락 앤 롤 가사.",
    placeSetting: "장대비가 세차게 쏟아지는 도심 빌딩 옥상",
  },
  {
    id: "runaway-highway-star",
    title: "고속도로 위의 야생마 (Wild Highway Star)",
    categoryId: "rock-metal",
    subTopicId: "youth-rebel",
    mood: "도시적인",
    vocal: "여성 솔로",
    instrument: "기타",
    tempo: "135-155 BPM",
    keywords: ["속도", "엔진", "질주", "탈출"],
    description: "오토바이를 타고 자정의 고속도로를 시속 150km로 질주하며 내일이 없는 듯 노래하는 펑크 락.",
    lyricsBackground: "사슬처럼 묶여 있던 일상에서 완전히 벗어나, 불타는 헤드라이트 불빛에 모든 걱정을 태워버리는 와일드하고 파워풀한 여성 보컬 중심의 스트레이트 하드락.",
    placeSetting: "끝없이 뻗어 있는 황량한 심야 국도",
  },
  {
    id: "broken-mirror-screamer",
    title: "깨진 거울 속의 분열 (Broken Mirror)",
    categoryId: "rock-metal",
    subTopicId: "heavy-heart",
    mood: "애절한",
    vocal: "남성 솔로",
    instrument: "기타",
    tempo: "120-140 BPM",
    keywords: ["거울", "파편", "분노", "그림자"],
    description: "내 안의 모순과 상처를 보며 거울을 깨부수고, 새로운 나를 찾기 위해 처절하게 울부짖는 곡.",
    lyricsBackground: "점점 무너져가는 자아와 심리적인 갈등을 무겁고 하드한 8현 일렉트릭 기타 튜닝과 투베이스 드럼의 파괴적인 리듬으로 표현한 포스트 하드코어 메탈 가사.",
    placeSetting: "깨진 유리 조각들이 바닥에 흩어진 허름한 화장실 안",
  },
  {
    id: "neon-shadow-run",
    title: "네온 빛의 도시 그림자 (Shadow in Neon City)",
    categoryId: "rock-metal",
    subTopicId: "youth-rebel",
    mood: "도시적인",
    vocal: "여성 솔로",
    instrument: "기타",
    tempo: "125-145 BPM",
    keywords: ["네온", "그림자", "골목", "추적"],
    description: "도시의 그림자 속에 숨은 어둠을 파헤치며 밤의 정의를 세우는 다이내믹한 락 스타일 가사.",
    lyricsBackground: "어두운 밤거리를 헤쳐 나가는 고독한 주인공의 마음을 드러내듯, 묵직한 베이스 라인과 날카로운 일렉기타 리프가 어우러진 현대적인 팝 펑크/얼터너티브 락 트랙.",
    placeSetting: "습기가 차오르는 새벽 도심의 어두운 뒤골목",
  },
  {
    id: "rust-and-chains",
    title: "녹슨 사슬을 끊고 (Breaking Rust)",
    categoryId: "rock-metal",
    subTopicId: "heavy-heart",
    mood: "애절한",
    vocal: "듀엣",
    instrument: "기타",
    tempo: "130-150 BPM",
    keywords: ["사슬", "자유", "비명", "희망"],
    description: "오랫동안 옥죄어 오던 정신적 쇠사슬을 마침내 스스로 끊어내고 외치는 부활과 승리의 포효.",
    lyricsBackground: "남녀 보컬이 절규하듯 주고받으며 클라이맥스로 치닫는 사운드. 웅장한 코러스와 심장을 고동치게 만드는 메탈기타 리프, 폭발적인 드럼 연주가 희망찬 승리감을 전함.",
    placeSetting: "녹슨 철창과 파이프들이 가득한 버려진 공장 내부",
  },
];
