import type { LyricsHubTemplate } from "../types";

export const spaceDreamyTemplates: LyricsHubTemplate[] = [
  {
    id: "starlight-nebula-whisper",
    title: "성운 속의 비밀 (Whisper in the Nebula)",
    categoryId: "space-dreamy",
    subTopicId: "starlight-galaxy",
    mood: "몽환적인",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "80-95 BPM",
    keywords: ["은하수", "신비함", "성운", "별자리"],
    description: "무한한 성운의 가스 구름 속에서 속삭이듯 찾아오는 내면의 은밀한 이야기와 그리움을 노래한 곡.",
    lyricsBackground: "어두운 밤하늘 너머 수천 광년 떨어진 푸른 성운을 망원경으로 관찰하며, 마치 우주 공간에 부유하듯 나른하고 신비로운 분위기를 연출한 일렉트로니카 신스 패드 발라드.",
    placeSetting: "별자리가 가득 쏟아지는 사막 한가운데 야외 천문대",
  },
  {
    id: "dreaming-ring-saturn",
    title: "토성의 고리 위에서 (On the Rings of Saturn)",
    categoryId: "space-dreamy",
    subTopicId: "dream-planet",
    mood: "몽환적인",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "85-100 BPM",
    keywords: ["행성", "토성", "얼음조각", "스케이트"],
    description: "토성의 아름다운 고리 위를 미끄러지듯 스케이트 타며 우주적 상상력과 꿈을 그리는 나른한 트랙.",
    lyricsBackground: "가상의 우주복을 입고, 웅장한 가스 행성 토성의 얼음 고리 위에서 은하수 물결을 향해 손짓하는 동화 같은 분위기. 영롱한 벨(Bell) 소리와 깊은 에코 보컬이 신비로움을 자아냄.",
    placeSetting: "토성의 고리 위, 얼음과 우주 먼지가 반짝이는 가상 트랙",
  },
  {
    id: "lonely-space-rover",
    title: "외로운 탐사선의 궤도 (Orbit of Lonely Voyager)",
    categoryId: "space-dreamy",
    subTopicId: "starlight-galaxy",
    mood: "잔잔한",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "70-85 BPM",
    keywords: ["탐사선", "신호음", "태양계", "외로움"],
    description: "아득한 태양계 너머 심우주를 비행하며 지구에 보낼 신호음을 연주하는 쓸쓸하고 정교한 연가.",
    lyricsBackground: "수십 년간 어두운 무중력 공간을 여행 중인 보이저호의 시선으로, 태양빛마저 희미해진 차가운 진공 속에서 잊힌 사랑을 끊임없이 전파로 발신하는 고독을 앰비언트 락으로 표현.",
    placeSetting: "태양계 끝자락을 외로이 떠돌아다니는 탐사선 안",
  },
  {
    id: "supernova-explosion-love",
    title: "초신성 폭발의 순간 (Supernova Burst)",
    categoryId: "space-dreamy",
    subTopicId: "dream-planet",
    mood: "몽환적인",
    vocal: "듀엣",
    instrument: "신스",
    tempo: "110-125 BPM",
    keywords: ["초신성", "폭발", "빛", "영원"],
    description: "별의 수명이 다해 터지며 남기는 가장 눈부신 빛에 빗대어 우리의 찬란했던 만남을 노래하는 곡.",
    lyricsBackground: "사라지는 것은 슬프지만, 우주에서 가장 뜨겁고 아름다운 잔해를 남겨 다시 먼지가 되어 만날 것이라는 심오한 윤회적 사랑 고백. 벅찬 드럼 빌드업과 찬란한 일렉 신스가 돋보임.",
    placeSetting: "오로라가 휘몰아치며 우주 폭풍이 일어나는 가상의 행성 지표면",
  },
  {
    id: "meteor-shower-wishes",
    title: "유성우 속의 소원 (Wishes in the Meteor Shower)",
    categoryId: "space-dreamy",
    subTopicId: "starlight-galaxy",
    mood: "잔잔한",
    vocal: "듀엣",
    instrument: "신스",
    tempo: "75-90 BPM",
    keywords: ["유성우", "소원", "야외", "침묵"],
    description: "수많은 별똥별이 떨어지는 깊은 밤 잔디밭에 누워 평생 잊지 못할 추억을 아로새기는 듀엣곡.",
    lyricsBackground: "지구로 떨어지는 우주 먼지들의 눈부신 비를 보며, 서로의 소원을 조용히 속삭이며 미소를 짓는 서정적인 어반 신스 팝. 맑은 어쿠스틱 피아노와 공간감 넘치는 패드 소리가 매력적.",
    placeSetting: "도시 불빛이 닿지 않는 어두운 산꼭대기 푸른 잔디 언덕",
  },
  {
    id: "anti-gravity-dancing",
    title: "무중력 댄싱 (Dancing in Zero Gravity)",
    categoryId: "space-dreamy",
    subTopicId: "dream-planet",
    mood: "몽환적인",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "95-110 BPM",
    keywords: ["무중력", "공중부양", "유영", "해방"],
    description: "중력이 사라져 공중으로 둥둥 떠오르는 듯한 자유로움과 몽환적인 해방감을 표현한 가사.",
    lyricsBackground: "나를 짓누르던 세상의 무게를 털어버리고 몸이 붕 뜬 채 밤하늘을 유영하는 기분. 몽환적인 보컬 찹(Vocal Chops)과 부드러운 드럼 앤 베이스(DnB) 리듬이 상쾌함을 줌.",
    placeSetting: "푸른 지구의 둥근 곡선이 유리창 너머로 선명히 비치는 우주선 관측소",
  },
];
