import type { LyricsHubTemplate } from "../types";

export const themeTemplates: LyricsHubTemplate[] = [
  // ==========================================
  // 1. 사랑 / 설렘 (love-romance)
  // ==========================================
  {
    id: "cherry-blossom-confess",
    title: "벚꽃 그늘 아래의 첫 고백 (First Blossom Confession)",
    categoryId: "love-romance",
    subTopicId: "fluttering-start",
    mood: "도시적인",
    vocal: "여성 솔로",
    instrument: "기타",
    tempo: "80-95 BPM",
    keywords: ["벚꽃", "봄바람", "고백", "첫사랑"],
    description: "봄바람에 벚꽃 잎이 흩날리는 거리에서 고백을 앞두고 떨리는 감정을 노래하는 러브송.",
    lyricsBackground: "내 볼을 스치는 따스한 바람처럼 맑고 깨끗한 톤의 보컬과 경쾌한 어쿠스틱 기타 리듬이 돋보이는 곡. 너를 만난 순간부터 벚꽃처럼 핑크빛으로 물든 마음을 묘사.",
    placeSetting: "벚꽃이 눈처럼 흩날리는 따뜻한 봄날의 가로수길 아래",
  },
  {
    id: "cafe-window-seat",
    title: "카페 창가 너와의 소소한 나날 (Cozy Cafe Romance)",
    categoryId: "love-romance",
    subTopicId: "sweet-daily",
    mood: "잔잔한",
    vocal: "듀엣",
    instrument: "피아노",
    tempo: "75-90 BPM",
    keywords: ["커피", "데이트", "산책", "눈빛"],
    description: "매일 찾는 카페 창가 자리에 나란히 앉아 차를 마시며 눈을 맞추는 소소한 일상 연가.",
    lyricsBackground: "혼성 듀엣의 따뜻하고 감미로운 화음이 잔잔한 피아노 반주 위에 실려 흘러감. 특별한 이벤트는 없어도 오직 서로가 곁에 있기에 소중한 하루의 질감.",
    placeSetting: "오후의 따뜻한 햇살이 비쳐 드는 동네 단골 카페 창가석",
  },
  {
    id: "under-same-umbrella",
    title: "한 우산 속의 거리 (Two Under One Umbrella)",
    categoryId: "love-romance",
    subTopicId: "fluttering-start",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "85-100 BPM",
    keywords: ["우산", "소나기", "어깨", "두근두근"],
    description: "갑작스러운 소나기에 좁은 우산 하나를 나눠 쓰고 걸으며 닿을 듯 말 듯 설레는 순간.",
    lyricsBackground: "어깨가 부딪힐 때마다 조금씩 요동치는 심장 소리. 내 어깨는 젖어도 상관없으니 네가 젖지 않게 우산을 기울여주는 풋풋하고 낭만적인 고백 송.",
    placeSetting: "장마철 혹은 소나기가 내리는 도심 인도 위",
  },

  // ==========================================
  // 2. 이별 / 슬픔 (breakup-sadness)
  // ==========================================
  {
    id: "empty-chair-remains",
    title: "네가 앉아 있던 빈자리 (Your Empty Seat)",
    categoryId: "breakup-sadness",
    subTopicId: "after-farewell",
    mood: "쓸쓸한",
    vocal: "여성 솔로",
    instrument: "피아노",
    tempo: "60-75 BPM",
    keywords: ["방안", "빈자리", "흔적", "지갑"],
    description: "이별 후 돌아온 방 안에서, 네가 남겨둔 사소한 흔적들을 마주하며 참았던 눈물을 터뜨리는 가사.",
    lyricsBackground: "서랍장 속 네가 두고 간 물건, 식탁 위 마주 앉았던 의자를 멍하니 바라보며 밀려오는 헤어짐의 무게. 서정적이고 절제된 건반 터치와 슬픈 보컬 톤이 돋보이는 정통 마이너 발라드.",
    placeSetting: "혼자 남겨진 적막하고 차가운 아파트 거실",
  },
  {
    id: "delete-phone-number",
    title: "지우지 못한 열 한 자리 (Unsaved Contact)",
    categoryId: "breakup-sadness",
    subTopicId: "painful-memory",
    mood: "애절한",
    vocal: "남성 솔로",
    instrument: "피아노 & 스트링",
    tempo: "70-85 BPM",
    keywords: ["전화기", "연락처", "망설임", "삭제"],
    description: "스마트폰 주소록에서 이름을 지웠음에도, 머릿속엔 번호가 너무나 또렷해 괴로워하는 심경.",
    lyricsBackground: "전화번호를 입력했다 지웠다 반복하는 지루한 밤샘. 혹시나 발신 제한으로 걸어볼까 망설이는 어리석은 미련을 오케스트레이션 발라드로 극적으로 표현.",
    placeSetting: "어둠에 잠긴 새벽 2시, 침대 위 흐릿한 폰 액정 앞",
  },
  {
    id: "tear-stained-photo",
    title: "눈물로 흐려진 폴라로이드 (Tear-Stained Polaroid)",
    categoryId: "breakup-sadness",
    subTopicId: "after-farewell",
    mood: "아련한",
    vocal: "듀엣",
    instrument: "기타 & 피아노",
    tempo: "65-80 BPM",
    keywords: ["사진", "추억", "미안함", "눈물"],
    description: "함께 찍은 폴라로이드 사진 속 행복했던 미소와 대조되는 현실의 이별을 서글프게 노래한 곡.",
    lyricsBackground: "시간이 지나 색 바랜 사진 속 너와 나. 미안하다는 말 한마디 못 한 채 돌아서야 했던 서로의 아쉬움을 잔잔한 듀엣 하모니로 조율하며 부르는 서정 가요.",
    placeSetting: "먼지가 살짝 앉은 책상 서랍장 안 수첩 사이",
  },

  // ==========================================
  // 3. 위로 / 치유 (comfort-healing)
  // ==========================================
  {
    id: "subway-tired-shoulder",
    title: "막차 버스의 지친 어깨 (Comfort on the Last Bus)",
    categoryId: "comfort-healing",
    subTopicId: "walking-home",
    mood: "잔잔한",
    vocal: "남성 솔로",
    instrument: "기타",
    tempo: "70-85 BPM",
    keywords: ["퇴근", "지하철", "한숨", "수고했어"],
    description: "힘겨운 하루를 마치고 막차를 타고 귀가하는 지친 사람들에게 건네는 따뜻하고 소박한 위로.",
    lyricsBackground: "창에 머리를 기대고 조는 이들의 무거운 가방과 발걸음을 보며, '오늘도 정말 애썼다'고 가만히 토닥여주는 따스한 통기타 포크 위로곡.",
    placeSetting: "밤 11시 30분, 도심 외곽으로 향하는 심야 광역버스 창가",
  },
  {
    id: "warm-hug-friend",
    title: "언제나 든든한 너의 그늘 (A Cozy Shelter for You)",
    categoryId: "comfort-healing",
    subTopicId: "warm-hug",
    mood: "잔잔한",
    vocal: "여성 솔로",
    instrument: "피아노",
    tempo: "75-90 BPM",
    keywords: ["포옹", "친구", "햇살", "지탱"],
    description: "인생의 풍파 속에서 흔들릴 때 말없이 다가와 안아주던 소중한 존재에 대한 고마움을 표현.",
    lyricsBackground: "잔잔한 피아노와 스트링이 따뜻하게 보컬을 감싸 안음. 혼자가 아님을 일깨워주며 깊은 슬픔에서 건져 올려주는 힐링 발라드 스타일의 가사.",
    placeSetting: "비가 그치고 맑게 갠 오후, 볕이 잘 드는 벤치 위",
  },
  {
    id: "tears-dry-tomorrow",
    title: "눈물은 흐르고 내일은 뜬다 (Tears Flow, Tomorrow Glows)",
    categoryId: "comfort-healing",
    subTopicId: "walking-home",
    mood: "잔잔한",
    vocal: "듀엣",
    instrument: "기타",
    tempo: "80-95 BPM",
    keywords: ["눈물", "아침", "햇살", "다짐"],
    description: "오늘 밤 마음껏 울고 나면 내일은 더 맑고 깨끗한 아침 햇살을 마주할 것이라는 격려의 찬가.",
    lyricsBackground: "어두운 터널도 결국 끝이 있듯이, 현재의 시련은 밝게 빛날 봄날을 준비하는 과정임을 차분하고 희망찬 혼성 어쿠스틱 선율로 풀어냄.",
    placeSetting: "동이 트기 시작하는 이른 새벽의 옥상 난간 앞",
  },

  // ==========================================
  // 4. 청춘 / 해방 (youth-freedom)
  // ==========================================
  {
    id: "unmapped-ocean-voyage",
    title: "지도가 없는 바다로 (Voyage to Unmapped Ocean)",
    categoryId: "youth-freedom",
    subTopicId: "new-departure",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "기타",
    tempo: "120-140 BPM",
    keywords: ["바다", "깃발", "도전", "지도"],
    description: "정해진 항로가 없더라도 오직 심장의 나침반만을 믿고 돛을 올리는 청춘의 모험과 패기.",
    lyricsBackground: "신나는 일렉기타 드라이브와 경쾌한 드럼 비트 위에 시원하게 내지르는 보컬. 미래에 대한 불안감을 거친 파도 삼아 넘어서겠다는 자유 가득한 펑크/팝 락.",
    placeSetting: "시원한 파도와 파란 바다가 끝없이 펼쳐진 배 위 수평선 앞",
  },
  {
    id: "twenty-confused-mirror",
    title: "스물의 삐걱거리는 거울 (Confused Mirror of Twenty)",
    categoryId: "youth-freedom",
    subTopicId: "growth-pain",
    mood: "쓸쓸한",
    vocal: "여성 솔로",
    instrument: "기타",
    tempo: "90-110 BPM",
    keywords: ["스무살", "거울", "시간", "불안"],
    description: "대학 혹은 첫 직장에서 낯선 사회적 역할에 흔들리는 스무 살 청춘의 아픈 성장통 독백.",
    lyricsBackground: "거울에 비친 어색한 내 모습을 보며, 완벽하지 않아도 그것 자체로 소중한 시절임을 담담하게 독백하듯 읊조리는 모던 락/포크 계열의 가사.",
    placeSetting: "좁고 어수선하지만 꿈이 묻어나는 대학교 근처 자취방 화장대 거울 앞",
  },
  {
    id: "escape-weekend-highway",
    title: "탈출의 엑셀러레이터 (Highway Escape)",
    categoryId: "youth-freedom",
    subTopicId: "new-departure",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "128 BPM",
    keywords: ["엑셀", "탈출", "모험", "바인드"],
    description: "구속과 속박이 없는 곳을 향해 핸들을 잡고 주말 새벽 질주하는 청춘의 속도감 넘치는 곡.",
    lyricsBackground: "화려한 신스웨이브 베이스 리듬과 청량감 넘치는 비트가 만나 질주 쾌감을 선사함. 백미러 뒤로 사라지는 도심의 네온사인을 뒤로하고 영원을 향해 달리는 역동적 보컬 가사.",
    placeSetting: "금요일 밤에서 토요일 아침으로 넘어가는 시간대의 도심 외곽 고속도로",
  },

  // ==========================================
  // 5. 레트로 / 추억 (retro-nostalgia)
  // ==========================================
  {
    id: "cassette-pencil-rewind",
    title: "카세트 테이프와 연필 한 자루 (Pencil & Cassette Rewind)",
    categoryId: "retro-nostalgia",
    subTopicId: "cassette-tape",
    mood: "잔잔한",
    vocal: "여성 솔로",
    instrument: "기타",
    tempo: "70-85 BPM",
    keywords: ["카세트", "연필", "이어폰", "옛날노래"],
    description: "늘어진 카세트테이프 테두리를 연필로 돌려 감아 다시 듣던 아날로그 시절의 아련한 사랑 추억.",
    lyricsBackground: "카세트 A면 마지막 트랙에 녹음되어 있던 상대방의 목소리와 노이즈 가득한 노래. 빈티지한 피아노와 따뜻한 어쿠스틱 기타 아르페지오가 더해진 서정적인 레트로 포크 송.",
    placeSetting: "먼지 쌓인 카세트 플레이어가 놓여 있는 방 안 나무 책상 앞",
  },
  {
    id: "alleyway-sunset-play",
    title: "골목길 저녁노을의 술래잡기 (Sunset Hide and Seek)",
    categoryId: "retro-nostalgia",
    subTopicId: "old-neighborhood",
    mood: "잔잔한",
    vocal: "남성 솔로",
    instrument: "피아노 & 기타",
    tempo: "75-90 BPM",
    keywords: ["골목", "저녁노을", "동네", "아이들"],
    description: "어스름해진 골목길에서 밥 먹으러 들어오라 부르던 어머니의 외침과 그때 그 시절 친구들의 미소.",
    lyricsBackground: "엄마의 부름에 아쉬워하며 흩어지던 흙먼지 가득한 동네 골목. 지금은 사라진 평상에 앉아 붉게 물드는 저녁하늘을 바라보며 쓸쓸하지만 아늑하게 추억을 어루만지는 힐링 곡.",
    placeSetting: "오래된 한옥과 담벼락이 늘어선 고향 동네 좁은 골목길 초입",
  },
  {
    id: "vintage-diary-letter",
    title: "바랜 일기장의 편지 (Faded Diary Letter)",
    categoryId: "retro-nostalgia",
    subTopicId: "cassette-tape",
    mood: "아련한",
    vocal: "듀엣",
    instrument: "기타 & 피아노",
    tempo: "65-80 BPM",
    keywords: ["수첩", "연필", "편지", "우표"],
    description: "학창시절 주고받던 비밀 교환일기장을 서랍 속에서 찾아 열어보며 짓는 아련한 미소.",
    lyricsBackground: "삐뚤빼뚤 쓴 글씨들과 낙서가 가득한 오래된 일기장 속 우리들의 다짐. 이제는 어엿한 어른이 된 두 사람이 그 시절 순수를 회고하는 따스하고 빈티지한 혼성 발라드.",
    placeSetting: "낡은 가죽 상자가 놓여 있는 다락방 한편",
  },
];
