import type { LyricsHubTemplate } from "../types";

export const trotTemplates: LyricsHubTemplate[] = [
  {
    id: "soju-glass-life",
    title: "인생은 꺾기 한 판 (Life is a Twist)",
    categoryId: "trot",
    subTopicId: "life-stage",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "135-155 BPM",
    keywords: ["술잔", "어머니", "인생길", "고개"],
    description: "한 잔 술에 슬픔을 털어내고, 내일은 해 뜰 날이라며 어깨춤을 추는 인생의 애환을 담은 곡.",
    lyricsBackground: "굽이굽이 험한 인생 고개를 넘으며 흘린 땀방울을 달콤한 멜로디와 어쿠스틱 아코디언, 브라스 사운드로 흥겹게 위로하는 세미 트로트 가사.",
    placeSetting: "하루 일과가 끝난 후 포장마차 안, 노란 전등 불빛 아래",
  },
  {
    id: "traditional-market-laugh",
    title: "장터의 꽃순이 (Flower of the Market)",
    categoryId: "trot",
    subTopicId: "old-market",
    mood: "도시적인",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "140-160 BPM",
    keywords: ["시장", "정", "웃음", "흥"],
    description: "시끌벅적한 전통시장에서 열심히 손님을 맞이하며 씩씩하게 살아가는 과일가게 꽃순이의 이야기.",
    lyricsBackground: "정이 넘치는 시장 상인들의 따뜻한 말 한마디와 장터의 왁자지껄한 활기. 신나는 국악 타악기와 일렉트로닉 트로트 비트가 어우러져 남녀노소 즐길 수 있는 댄스 트로트.",
    placeSetting: "왁자지껄 흥이 넘치는 주말 오후의 시골 오일장 터",
  },
  {
    id: "express-train-love",
    title: "사랑의 고속열차 (Love Express Train)",
    categoryId: "trot",
    subTopicId: "life-stage",
    mood: "도시적인",
    vocal: "여성 솔로",
    instrument: "신스",
    tempo: "145-160 BPM",
    keywords: ["기차", "플랫폼", "사랑", "속도"],
    description: "님을 향해 멈추지 않고 달려가는 사랑을 고속열차에 빗대어 경쾌하게 표현한 트랙.",
    lyricsBackground: "사랑은 타이밍! 머뭇거리지 말고 내 마음의 기차표를 끊으라는 재치 있고 중독성 있는 후렴구. 브라스 섹션의 화려한 드라이브와 빠른 디스코 템포가 특징.",
    placeSetting: "기차가 출발하기 직전, 만남과 헤어짐이 있는 서울역 플랫폼",
  },
  {
    id: "mother-worn-hands",
    title: "엄마의 하얀 손가락 (Mother's Worn Hands)",
    categoryId: "trot",
    subTopicId: "life-stage",
    mood: "애절한",
    vocal: "여성 솔로",
    instrument: "피아노",
    tempo: "70-90 BPM",
    keywords: ["어머니", "세월", "손자국", "사랑"],
    description: "자식들을 위해 평생 고생하시느라 거칠어진 어머니의 손을 보며 뜨거운 눈물을 흘리는 애절한 가사.",
    lyricsBackground: "자식들이 잘 되기만을 기도하며 닳아버린 어머니의 세월과 헌신에 보답하겠다는 절절한 효심을 담아냄. 대금과 오케스트라 현악기가 슬프게 어우러지는 전통 락 트로트.",
    placeSetting: "명절날 저녁, 따뜻한 온기가 가득한 고향 집 안방",
  },
  {
    id: "country-bus-stop",
    title: "기다려라 내 청춘 (Wait For Me, My Youth)",
    categoryId: "trot",
    subTopicId: "old-market",
    mood: "도시적인",
    vocal: "남성 솔로",
    instrument: "신스",
    tempo: "130-145 BPM",
    keywords: ["정류장", "버스", "고향", "동네"],
    description: "도심을 떠나 흙내음 가득한 고향 동네 버스 정류장에 내리며 다시금 열정을 불태우는 중년의 찬가.",
    lyricsBackground: "세상살이에 지쳐 지친 몸을 이끌고 찾아간 고향 길에서, 다시 한번 활기를 얻고 힘차게 도약하겠다는 외침. 신나는 트롬본과 트럼펫 멜로디가 어깨를 들썩이게 함.",
    placeSetting: "코스모스가 길가에 흐드러진 시골 정류장 앞",
  },
  {
    id: "market-love-spark",
    title: "사랑은 시장통 야시장 (Midnight Market Romance)",
    categoryId: "trot",
    subTopicId: "old-market",
    mood: "도시적인",
    vocal: "듀엣",
    instrument: "신스",
    tempo: "135-150 BPM",
    keywords: ["야시장", "떡볶이", "등불", "장난"],
    description: "왁자지껄한 야시장에서 맛있는 음식을 함께 먹으며 눈이 맞은 상인 남녀의 아기자기한 밀당 소동.",
    lyricsBackground: "맛있는 음식 냄새와 화려한 전등 불빛 가득한 밤. 옥신각신하면서도 서로를 챙겨주는 달콤한 모습을 주고받는 남녀 듀엣곡. 휘파람 소리와 어쿠스틱 피아노가 경쾌함을 더함.",
    placeSetting: "화려한 붉은색 등불들이 켜진 시끌벅적한 밤 야시장 거리",
  },
];
